vmware/pyvcloud

pyvcloud/gateway.py
pyvcloud/vapp.py
pyvcloud/vcloudair.py

Add support for DHCP and firewall rules  in gateway.
Add vdc network create/delete to vcloudair/

DHCP, Firewall and vdc network improvements

---

pyvcloud/vcloudair.py

Add deploy and poweron settings to
the method arguments. Set default
value for deploy to false.

Fix create_vapp

---

pyvcloud/vcloudair.py

Before: "Network reated by pyvcloud"
After: "Network сreated by pyvcloud"
In line 530

Fix spelling error

---

pyvcloud/vcloudair.py

Hi, adding network did not have the create_vdc_network did not have verify=self.verify in the post and therefore failed to add network in insecure mode.

fixed bug in network not using insecure connection

---

pyvcloud/gateway.py
pyvcloud/vapp.py

Add new properties:
is_primary
allocation_mode
to vms_network_info result list

Add new properties to vms_network_info

---

pyvcloud/vcloudair.py

Before fix if self.response.history is empty list, the  statement:
self.response.history[-1]
raise exeption: IndexError: list index out of range

Add checks: list has elements.

---

pyvcloud/vapp.py

Network interface

---

pyvcloud/score.py
requirements.txt

Send archive using Streaming Uploads

SCOR-5 Change the Score Rest server to allow ids without Org-ids

---

pyvcloud/vcloudair.py
tests/vcloud_tests.py

removes the SourcedItem tag being implemented in versions == 5.5 and older.
Should resolve issues #61, and #41

Fixes issues #62

---

pyvcloud/gateway.py
pyvcloud/score.py
pyvcloud/vcloudair.py

Add "busy" flag for verifying status of gateway.
User can check this flag before update gateway.

Add busy flag to gateway.

---

pyvcloud/exceptions.py
pyvcloud/score.py

- Added client exceptions
- Small style fixes

Adds a flexible error handling

---

pyvcloud/score.py

NOTE: this change is a dependency for vca-cli latest code

Improve Score user experience

---

pyvcloud/schema/vcd/schemas/versioning/versionsType.py
pyvcloud/schema/vcd/v1_5/schemas/admin/vCloudEntities.py
pyvcloud/schema/vcd/v1_5/schemas/vcloud/catalogItemType.py
pyvcloud/schema/vcd/v1_5/schemas/vcloud/catalogType.py
pyvcloud/schema/vcd/v1_5/schemas/vcloud/commonType.py
pyvcloud/schema/vcd/v1_5/schemas/vcloud/diskType.py
pyvcloud/schema/vcd/v1_5/schemas/vcloud/entityType.py
pyvcloud/schema/vcd/v1_5/schemas/vcloud/mediaType.py
pyvcloud/schema/vcd/v1_5/schemas/vcloud/networkType.py
pyvcloud/schema/vcd/v1_5/schemas/vcloud/organizationListType.py
pyvcloud/schema/vcd/v1_5/schemas/vcloud/organizationType.py
pyvcloud/schema/vcd/v1_5/schemas/vcloud/queryRecordViewType.py
pyvcloud/schema/vcd/v1_5/schemas/vcloud/sessionType.py
pyvcloud/schema/vcd/v1_5/schemas/vcloud/taskType.py
pyvcloud/schema/vcd/v1_5/schemas/vcloud/tasksListType.py
pyvcloud/schema/vcd/v1_5/schemas/vcloud/vAppTemplateType.py
pyvcloud/schema/vcd/v1_5/schemas/vcloud/vAppType.py
pyvcloud/schema/vcd/v1_5/schemas/vcloud/vcloudType.py
pyvcloud/schema/vcd/v1_5/schemas/vcloud/vdcType.py
pyvcloud/schema/vcd/v1_5/schemas/vcloud/vmsType.py
pyvcloud/schema/vchs/ondemand/sc/sc/bindingType.py
pyvcloud/schema/vchs/ondemand/sc/sc/instanceType.py
pyvcloud/schema/vchs/ondemand/sc/sc/serviceplanType.py
pyvcloud/schema/vcim/baseType.py
pyvcloud/schema/vcim/errorType.py
pyvcloud/schema/vcim/serviceType.py
pyvcloud/schema/vcim/sessionType.py
pyvcloud/schema/vcim/vchsType.py

Make exception block syntax py3-compatible

Make exception block syntax py3-compatible

---

pyvcloud/__init__.py
pyvcloud/gateway.py
pyvcloud/helper/CommonUtils.py
pyvcloud/vapp.py
pyvcloud/vcloudair.py
pyvcloud/vcloudsession.py
setup.py
tests/catalog_tests.py
tests/connect_vapp_to_network.py
tests/login_to_score.py
tests/net_tests.py
tests/pyvcloud_tests.py
tests/score_tests.py
tests/sqlair_tests.py
tests/vapp_tests.py
tests/vapp_vm_tests.py
tests/vca_sso_tests.py
tests/vca_tests.py
tests/vca_type_tests.py
tests/vca_user_tests.py
tests/vcloud_tests.py
tests/vdc_tests.py

This Pull Request adds the ability to recompose vApps, to add or remove virtual machines to or from vApps (resolves issue #21 for @akulkarni-rvbd, @xcompass, @sanderv32). It also adds the ability to clone vApps to a new vApp in the same or a different VDC.
Also, the network settings passed to create_vapp (issue #40) will now have effect.

Compose & clone vApp

---

pyvcloud/vcd/client.py

- This client library includes all of the necessary components for
vCloud Director API access:
- Task monitor
- Well known endpoints enumeration
- LinkType management and validation
- Query Service interaction

client: Introduce library suitable for efficient vCD API access

---

AUTHORS
CONTRIBUTING.md
ChangeLog
pyvcloud/vcd/vdc.py
tests/vcd_vapp.py

See commit messages for details

no guest customization

---

pyvcloud/vcd/vdc.py
tests/vcd_vapp.py

Added capability to instantiate a vApp with custom disk size
vApp instantiation can now happen for VDCs with no network,
Refactored the function vapp_instantiate() to rename few variables and moved around sections of code to tightly follow the order of creation of various elements of vAppTemplateInstantiationParam.
ToDo : Unit tests
Manually tested that the functionality is working as per design.

Adding capability to instantiate a vApp with custom disk size

---

README.md
pyvcloud/vcd/client.py
pyvcloud/vcd/org.py
pyvcloud/vcd/vdc.py
setup.cfg

see commit messages for details

instantiate_vapp customization

---

pyvcloud/vcd/org.py
tests/vcd_role.py
tests/vcd_user.py

When login as System admin and  in turn switched to 'orgAdmin', resource_type is 'adminRole'
When loged as 'orgAdmin' directly , resource_type is 'role'
```
C:\sources\github\service_ecosystem\vcd-cli (master)
(vcd-cli) λ vcd login 10.150.200.5 System administrator --no-verify-ssl-certs --password ca$hc0w
InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised.
administrator logged in, org: 'System', vdc: ''
C:\sources\github\service_ecosystem\vcd-cli (master)
(vcd-cli) λ vcd role list
InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised.
isReadOnly    name
------------  ----------------------------
true          System Administrator
true          Multisite System …
```

Fixing list_roles() and get_role() to work with org-admin

---

pyvcloud/vcd/client.py
pyvcloud/vcd/system.py
tests/vcd_system.py

VCDA-171(pyvcloud) - Create a new organization with just the mandatory user inputs

Create a new organization with just the mandatory user inputs

---

pyvcloud/vcd/org.py
tests/vcd_catalog_update.py

Added update_catalog function and unit test.

Curt branch

---

pyvcloud/vcd/client.py
pyvcloud/vcd/org.py
pyvcloud/vcd/vapp.py
pyvcloud/vcd/vdc.py
tests/vcd_disk.py
tests/vcd_vapp.py

Commands for changing owner for vApp and independent disks

Commands for changing owner for vApp and independent disks

---

ChangeLog
pyvcloud/vcd/client.py
pyvcloud/vcd/vapp.py
pyvcloud/vcd/vdc.py
tests/vcd_vapp.py

- add disk to vm
- fixed typo in vdc class
- flake8 validation
- renamed vApp getVmFromVApp to get_vm (underscore is preferred in python)

add disk to vm

---

pyvcloud/vcd/org.py
tests/vcd_user.py

Unit test :
(pyvcloud) C:\code\pyvcloud\tests>python -m unittest vcd_user.TestUser.test_create_and_delete_user
C:\Users\sena\Envs\pyvcloud\lib\site-packages\urllib3-1.22-py3.6.egg\urllib3\connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
InsecureRequestWarning)
None
.
Ran 1 test in 3.051s
OK

Implementation for deleting an user from organization

---

pyvcloud/vcd/org.py
tests/vcd_catalog.py

I had to create a new pull request after resolving few issues. Sorry for losing reviews on previous pull request. I have addressed all of them though.

Catalog change owner

---

pyvcloud/vcd/client.py
pyvcloud/vcd/org.py
pyvcloud/vcd/vapp.py
pyvcloud/vcd/vdc.py
tests/vcd_role.py
tests/vcd_user.py

Searched across all python files under \pyvcloud\pyvcloud\vcd and \pyvcloud\tests to make sure that all instances of org.is_admin has been replaced with the new logic. Additionally ran flake8 validation over the entire project to make sure that nothing is broken.

Refactoring is_admin field in org.py to client.py

---

pyvcloud/vcd/org.py
pyvcloud/vcd/system.py
pyvcloud/vcd/test.py
pyvcloud/vcd/utils.py
tests/vcd_org.py
tests/vcd_system.py
tests/vcd_user.py

1. Enable/Disable Org which is already created (via 'vcd org update <org_name>' command)
2. Add new option '--enable' to enable org during creation.
3. Enable/disable user which was already created. (via 'vcd user update <user_name>' command)
Review complete.
https://reviewable.io/reviews/anusuyar/pyvcloud/6#-

Enable/Disable Org, User. Add --enable option for create org.

---

pyvcloud/vcd/amqp.py
pyvcloud/vcd/client.py
pyvcloud/vcd/cluster.py
pyvcloud/vcd/extension.py
pyvcloud/vcd/org.py
pyvcloud/vcd/role.py
pyvcloud/vcd/system.py
pyvcloud/vcd/task.py
pyvcloud/vcd/test.py
pyvcloud/vcd/utils.py
pyvcloud/vcd/vapp.py
pyvcloud/vcd/vdc.py
pyvcloud/vcd/vsphere.py

To make pep8 validation easier, I ran `yapf` against `pyvcloud/vcd/*.py`. This PR only has formatting changes, it *should* not have any changes in the logic.

formatted with yapf

---

pyvcloud/vcd/org.py
tests/vcd_org.py

Review Done. https://reviewable.io/reviews/anusuyar/pyvcloud/7

 Removed org_name in the update_org

---

pyvcloud/vcd/client.py
pyvcloud/vcd/org.py
tests/vcd_role.py

Inspected code as per pep8 standards.

Create a role in the specified Org or current org in use

---

pyvcloud/vcd/org.py
tests/vcd_role_right.py

(vcd-cli) sayloo-m01:vcd-cli sayloo$ vcd role delete demoRole
Role 'demoRole' has been successfully deleted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/154)

[pyvcloud] Delete role from a given org

---

CONTRIBUTING.md

Restructured CONTRIBUTING.md to make it quick for experienced users but
also provide detailed instructions for new contributors, including those
for whom this is their first Github contribution.  Changes include
reordering to get most critical information in front and create a
soup-to-nuts example that illustrates Git commands and conventions to
follow for a successful pull request. (Based on CONTRIBUTING.md from
vmware/vcd-cli project.)
**Reviewers: this file is the same as vmware:vcd-cli/CONTRIBUTING.md with names changed from vcd-cli to pyvcloud.  See [vcd-cli PR 142](https://github.com/vmware/vcd-cli/pull/142)**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/153)

Improve CONTRIBUTING.md to make it more informative

---

pyvcloud/vcd/acl.py
pyvcloud/vcd/client.py
pyvcloud/vcd/org.py
tests/vcd_catalog.py

```
Implementing following commands
vcd catalog acl add <catalog-name> [subject:name:right]*
vcd catalog acl remove <catalog-name> [subject:name]*
vcd catalog acl share <catalog-name> --access-level ReadOnly
vcd catalog acl unshare <catalog-name>
vcd catalog acl list
vcd catalog acl info
C:\sources\github\service_ecosystem\vcd-cli (master)
(vcd-cli) λ vcd catalog acl add Test2 'org:AnuOrg1:ReadOnly'  'user:user:FullControl'
subject_name         subject_type    access_level
-------------------  --------------  --------------
AnuOrg (org_in_use)  org             None
AnuOrg1              org             ReadOnly
user                 user            FullControl
C:\sources\github\service_ecosystem\vcd-cli (master) 
(vcd-cli) λ vcd catalog acl remove Test2 'org:AnuOrg1'
subject_name …
```

Implementing catalog update acl commands

---

AUTHORS
ChangeLog
examples/list-vdc-resources.py
pyvcloud/vcd/vdc.py

- list-vdc-resources.py example
- minor VCD.list_resources refactor
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/170)

Added list resources example.

---

pyvcloud/vcd/client.py
pyvcloud/vcd/system.py
pyvcloud/vcd/utils.py

- more informative message when error is due to invalid session
- fix VCDA-399 show VDC info
- fixed errors due to insufficient access
- memory capacity in human format
These changes are to display more informative messages to users, no new functionality has been added and existing unit tests still apply.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/172)

VCDA-248 error handling on invalid session

---

pyvcloud/vcd/client.py
pyvcloud/vcd/org.py
pyvcloud/vcd/role.py
tests/vcd_role_right.py

1. New method to add new rights to a given organization.
2. New method to remove new rights from a given organization.
3. New method to list rights associated with a given organization.
4. Renamed existing method 'org.list_rights' to 'org.list_all_rights' as it lists all rights available in the System.
5. Minor refactoring of existing variable names.
6. Unit tests for add and remove rights from organization.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/174)

Add or remove rights from organization

---

pyvcloud/vcd/client.py
pyvcloud/vcd/platform.py
pyvcloud/vcd/vdc.py
tests/vcd_network.py

* Added two new functions in platform.py to list external networks and find one by it's name
* Refactored code to create directly connected org vdc network to leverage the functions mentioned above
* Removed slashes at the end of multi line function doc strings
* Converted VDC to lowercase in function doc strings
* Added unit test to test listing of all external networks
Unit test result
---------------
(pyvcloud) C:\code\pyvcloud\tests>python -m unittest vcd_network.TestNetwork.test_030_list_external_networks
.
Ran 1 test in 1.334s
OK
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/179)

VCDA-394: Introduce capability to list external networks

---

ChangeLog
pyvcloud/vcd/client.py
pyvcloud/vcd/org.py
pyvcloud/vcd/system.py
pyvcloud/vcd/task.py
tests/vcd_task.py

- fixes --no-wait flag
- list tasks by status
- wait for task by id
- option to overwrite catalog item when capturing vApp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/178)

VCDA-451: work with pending tasks

---

.travis.yml
ChangeLog
format-code.sh
pyvcloud/vcd/acl.py
pyvcloud/vcd/client.py
pyvcloud/vcd/extension.py
pyvcloud/vcd/org.py
pyvcloud/vcd/platform.py
pyvcloud/vcd/role.py
pyvcloud/vcd/system.py
pyvcloud/vcd/test.py
pyvcloud/vcd/vapp.py
pyvcloud/vcd/vdc.py
pyvcloud/vcd/vm.py
tox.ini

- use yapf to auto format code
- validate with flake8
- new ./format-code.sh script
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/183)

VCDA-409: validate PEP8 compliance

---

pyvcloud/vcd/vdc.py

- Corrected error message for non existent vapp to include vapp name
- No changes to existing tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/187)

VCDA-332 Correct error message for delete vapp

---

pyvcloud/vcd/client.py
pyvcloud/vcd/pvdc.py
pyvcloud/vcd/utils.py

- Implemented list storage profiles by implementing vcd-cli command 'pvdc info name'
- New pvdc.py module to manage pvdc resources.
- New utils method for format pvdc to dictionary.
Tested by vcd-cli tenant-onboard.sh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/188)

VCDA-441  list available storage profiles

---

requirements.txt

- Added version info to the required packages
- Sorted alphabetically
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/194)

Updated requirements with version info

---

pyvcloud/vcd/org.py
tests/vcd_user.py

C:\sources\github\service_ecosystem\vcd-cli (master)
(vcd-cli) λ vcd user list -o AnuOrg
deployedVMQuota    deployedVMQuotaRank  fullName    identityProviderType    isEnabled    isLdapUser    name        numberOfDeployedVMs    numberOfStoredVMs    storedVMQuota    storedVMQuotaRank
-----------------  ---------------------  ----------  ----------------------  -----------  ------------  --------  ---------------------  -------------------  ---------------  -------------------
0                     -1              INTEGRATED              true         false         user1                         0                    0                0                   -1
0                     -1              INTEGRATED              true         false         user2                         0 …

VCDA-473: Implement vcd user list command

---

AUTHORS
ChangeLog
pyvcloud/vcd/api_extension.py
pyvcloud/vcd/vapp.py
test-requirements.txt
tests/vcd_ext.py

- api extension operation now consider both name and namespace
- added unit tests
- minor re-format in VApp class
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/201)

VCDA-474: consider name and namespace in api extension

---

examples/make-vm-snapshot.py
pyvcloud/vcd/client.py
pyvcloud/vcd/vm.py
tests/vcd_vm.py

Implemented a function called snapshot_create in vm.py. So now we are able to create 
snapshots with this library.Also there is a small example script called 
make-vm-snapshot.py to demonstrate this functionality, along with a unit test case.

PR 199: Implement a snapshot creating function for vms

---

examples/system-info.py
examples/tenant-onboard.py
examples/vm-snapshot-tasks.py

Added check to see if new/existing user is enabled and enable same if
this is not the case.  Also cleaned up flake8 errors on sample scripts.
Reviewers: @sahithi , @rocknes, @sompa, @anusuyar

VCDA-519: Fixed tenant-onboarding.py example to enable user

---

pyvcloud/vcd/client.py
pyvcloud/vcd/platform.py
tests/vcd_vc.py

VDP-1375, VCDA-504: Attach VC
- Reviewers: @sompa @anusuyar
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/210)

VDP-1375, VCDA-504: Attach VC

---

.travis.yml
pyvcloud/vcd/test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/214)

travis build fix

---

.travis.yml
setup.cfg

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/215)

fix travis build

---

docs/install.md

Fixes the venv activation command in install.md

Fixes venv activation command

---

pyvcloud/vcd/exceptions.py

Created the new Exception class hierarchy for pyvcloud.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/230)

Exception class hierarchy implementation

---

pyvcloud/vcd/acl.py
pyvcloud/vcd/amqp.py
pyvcloud/vcd/client.py
pyvcloud/vcd/org.py
pyvcloud/vcd/platform.py
pyvcloud/vcd/pvdc.py
pyvcloud/vcd/role.py
pyvcloud/vcd/system.py
pyvcloud/vcd/vapp.py
pyvcloud/vcd/vdc.py
pyvcloud/vcd/vm.py

Refactored the pyvlcoud codebase to use the newly created Exception class hierarchy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/231)

Refactor Pyvcloud to use the new exception classes

---

pyvcloud/system_test_framework/base_test.py
pyvcloud/system_test_framework/environment.py
pyvcloud/vcd/client.py
system_tests/base_config.yaml
system_tests/vapp_tests.py
tests/vcd_vapp.py

1. Moved vApp tests from the old test files to the new framework
2. Added some new tests to test vApp operation which were untested as of now.
3. Enhanced environment.py to add an orgvdc network to the testing environment
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/236)

[VCDA-585] Add system tests for vApp

---

pyvcloud/system_test_framework/environment.py
pyvcloud/vcd/client.py
system_tests/base_config.yaml
system_tests/catalog_tests.py
system_tests/idisk_tests.py
system_tests/vapp_tests.py

* Introduced a method in environment.py to provide a logger object.
* Replaced all print statements with logger.debug statements
* Redirected client request logs into another log file for sanity of log mesaages
* Fixed an issue with logger in client.py and environment,py where we were adding multiple handlers to the same logger.
Ran idisk_tests.py, catalog_tests.py and vapp_tests.py to verify that logging is working as desired.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/246)

[VCDA-604] Convert all print statements in system tests to logger.debug statements

---

pyvcloud/vcd/client.py
pyvcloud/vcd/org.py
system_tests/catalog_tests.py
system_tests/vapp_tests.py

* Added missing doc-strings.
* Refactored implementation of catalog operations to use post/put/delete_linked_resource instead of hand crafted hrefs.
* Added Catalog system tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/247)

[VCDA-633 and VCDA-586] Refactored org.py and added catalog system tests

---

pyvcloud/vcd/client.py
pyvcloud/vcd/platform.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/251)

fixed media type (NSXT_MANAGERS -> NETWORK_MANAGERS)

---

pyvcloud/vcd/client.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/252)

deleted entity type NSXT_MANAGERS

---

AUTHORS
ChangeLog

* Merging auto generated files during release of pyvcloud v19.3.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/255)

Updated AUTHORS and ChangeLog for v19.3.0

---

.gitignore
examples/run_examples.sh
support/Dockerfile.build
support/Jenkinsfile
support/README.md
support/install.sh
support/lib.groovy
support/run_in_docker.sh
support/tox.sh
system_tests/run_system_tests.sh

* Update the Jenkins pipeline to allow more advanced functionality
* The Jenkins pipeline now works off of scripts that can run in the pipeline or in the user environment. The pipeline is also able to test remote repositories prior to accepting a pull request. See the support directory for more information.
* @hodgesrm, @rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/263)

[VCDA-689] Integrate generalized Jenkins build script

---

pyvcloud/system_test_framework/environment.py
pyvcloud/vcd/vapp.py
system_tests/idisk_tests.py
system_tests/vapp_tests.py

* Added functionality to query a vApp for it's power state
* Updated independent disk and vApp system tests to leverage the new functionality.
Ran idisks_tests and vapp_tests to verify that the changes didn't break any existing functionalities,
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/264)

[VCDA-333] Added functionality to query for vApp power state

---

pyvcloud/system_test_framework/environment.py
pyvcloud/vcd/vdc.py
system_tests/vdc_tests.py

* Added system tests for org vdc.
* Added a new method in environment.py to retrieve the name of test pvdc
Ran the test suite and all tests passed successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/272)

[VCDA-588] Implemented system tests for org VDC.

---

system_tests/network_tests.py

* Added new system tests for isolated orgvdc networks.
Ran the new tests, the run was successful without any errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/275)

[VCDA-589] Added network system tests.

---

pyvcloud/vcd/platform.py
system_tests/extnet_tests.py
system_tests/run_system_tests.sh

To help us process your pull request efficiently, please include:
Create & delete external network
Create an external network by providing name, VIM server name, portgroup names, gateway, netmask and IP ranges. Optional parameters are description, primary DNS, secondary DNS and DNS suffix. Delete an external network by providing the name. System tests for create and delete are added in a new test class.
@rajeshk2013 @rocknes @ckolovson
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/314)

[VP-1145,VP-1146] External Network: Create and Delete

---

pyvcloud/vcd/client.py
pyvcloud/vcd/vdc.py
system_tests/gateway_tests.py
system_tests/run_system_tests.sh

System user should be able to create gateway and delete them.
Added test case gateway_test.py for testing create and delete workflow.
@ckolovson @rocknes @shashim22 @hodgesrm
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/315)

[VP-1158 and VP-1156] Providing support for Gateway create and delete

---

pyvcloud/vcd/client.py
pyvcloud/vcd/gateway.py
system_tests/gateway_tests.py

User will be able to perform modify form factor. Supported value would be compact/full/full4/x-large.
In case value will not match from support list then it fails with InvalidParameterException.
Testing Done: Added test case
@shashim22 @pandeys @chaitanya118
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/321)

[VP-1247] Provided support for Modify form factor for gateway

---

pyvcloud/vcd/client.py
pyvcloud/vcd/platform.py
system_tests/base_config.yaml
system_tests/pvdc_tests.py
tox.ini

- Add/Delete storage profiles to a PVDC
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/318)

[VDP-2171]: Add/Delete storage profiles to a PVDC

---

pyvcloud/vcd/externalNetwork.py
pyvcloud/vcd/external_network.py
system_tests/extnet_tests.py

VP-1151: Add subnet to external network
User should be able to add subnet to existing external network.
Added test case for adding subnet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/323)

VP-1151: Add subnet to external network

---

pyvcloud/vcd/client.py
pyvcloud/vcd/gateway.py
system_tests/gateway_tests.py

Added function redeploy to gateway and a test case in system tests.
Added GATEWAY_REDEPLOY = 'edgeGateway:redeploy' to client along with YAPF formatting changes.
Testing done: ran the gateway_tests successfully.
@rajeshk2013 @shashim22
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/326)

VP-1160 : Redeploy edge gateway.

---

pyvcloud/vcd/client.py
pyvcloud/vcd/gateway.py
system_tests/gateway_tests.py

Added a function sync_syslog_settings to gateway.py and corresponding test cases.
Testing done: ran gateway_tests successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/327)

VP-1162: Synchronize syslog server settings of a gateway.

---

pyvcloud/vcd/vdc.py

Creation of vdc routed network was failing Bad Request exception in vCD. Seqeunce of elements in body was not correct.
Testing Done: Successfully run the Test case network_tests.py
@chaitanya118 @pandeys
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/342)

Fixing the order of request body

---

pyvcloud/vcd/gateway.py
system_tests/base_config.yaml
system_tests/constants.py
system_tests/gateway_tests.py

VP-1294,VP-1296:Add and Modify sub allocate pool of gateway
VP-1296: Adds the new ip range to the sub allocate pool of gateway
VP-1294:  Modify sub allocate pool range of gateway
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/344)

VP-1294,VP-1296:Add and Modify sub allocate pool of gateway

---

pyvcloud/vcd/vdc_network.py
system_tests/network_tests.py

User will be able to add multiple static pool for vdc routed network.
Testing Done: Added test case for this functionality and executed the complete vdc_network test class successfully.
@shashim22 @guptaankit52
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/361)

[VP-1359]Edit routed network for Static IP pool under Network Specification (Add)

---

pyvcloud/vcd/task.py

- Update Vcd task with stacktrace
- In addition to error message, task update now also includes stracktrace of the error
- Manual testing completed
@rocknes @rajeshk2013
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/353)

Add stacktrace support while updating Vcd task

---

pyvcloud/vcd/external_network.py
system_tests/extnet_tests.py
system_tests/gateway_tests.py

[PySdk] List gateway IP sub-allocation
This CLN contains functionality to list gateway ip sub acclocation. It
also has related test cases.
Testing done:
Test case for list associated ip sub allocation with gateway name  is
added to a test class extnet_tests.py
All tests in extnet_tests passed.
--- …

VP 1266: [PySdk] List gateway IP sub-allocation

---

pyvcloud/vcd/client.py
pyvcloud/vcd/gateway.py
pyvcloud/vcd/network_url_constants.py
pyvcloud/vcd/utils.py
system_tests/gateway_tests.py

This will create URL for Firewall from gateway URL. As there is no direct API to add new firewall rule, i am getting list of existing firewall rules and adding the
new one then do PUT request to vCD.
Testing Done: New test case has been added and executed the gateway_test class successfully
@shashim22 @chaitanya118
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/375)

[VP-1536] Add a Firewall Rule

---

pyvcloud/vcd/gateway.py
system_tests/gateway_tests.py

VP-1523: List Rate limits of the gateway 
VP-1628:  Disable rate limit of the gateway
Implemented list_rate_limits through which user would be able to list the rate limits of the gateway
Implemented disable_rate_limits through which user would be able to disable the rate limits of the gateway
Testing Done , all test cases are passing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/377)

VP-1523,VP-1628: List Rate limits of the gateway and disable rate limit

---

pyvcloud/vcd/external_network.py
system_tests/extnet_tests.py

List the vSphere Networks associated with external network.
Listing will be done in the below format:
[{'vCenter': 'vc1', 'Name': 'test-dvpg'}]       
Testing done:
Added the test case "test_0105_list_vsphere_network"
Test status : passed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/378)

VP-1602: List vSphere Networks

---

pyvcloud/vcd/gateway.py

VP-1658:List default config gateway
Fixed and refactored the List default config gateway
Testing:
All test cases are passing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/381)

VP-1658:List default config gateway

---

pyvcloud/vcd/gateway.py
pyvcloud/vcd/nat_rule.py
system_tests/nat_rule_tests.py

Edit various fields of a NAT Rule.
ex- originalAddress, translatedAddress and others.
Testing done:
Added "test_0030_update_nat_rule" test case.
status: passed
Adding optional field as per NSX guide, vnic=0 by default
vnic: interface of gateway
All the tests passed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/389)

VP-1586: Edit a NAT Rule

---

examples/tenant.yaml
pyvcloud/vcd/vdc_network.py
system_tests/network_tests.py

User can add and update the DNS values.
I made all the parameters of add_static_ip_pool_and_dns method optional so that on the need basis, user should be able to just update DNS or just add IP range. The way it works from vCD UI.
I added fix for below error as well.
https://sp-taas-vcd-butler.svc.eng.vmware.com/job/Preflight-pysdk-1.0-STF/27/console
----------
14:49:00   File "/data/jenkins/jenkins-Preflight-pysdk-1.0-STF-27/examples/tenant-onboard.py", line 245, in <module>
14:49:00     network_resource = vdc.create_isolated_vdc_network(**network)
14:49:00 TypeError: create_isolated_vdc_network() got an unexpected keyword argument 'gateway_ip'
---------
Testing Done: Added new method and executed successfully
@guptaankit52 @kousgy123
---
This change is [<img …

[VP-1363] Add DNS and Fixed failing test case

---

pyvcloud/system_test_framework/environment.py
pyvcloud/vcd/client.py
pyvcloud/vcd/vdc.py
system_tests/base_config.yaml
system_tests/gateway_tests.py

Gateway creation was failing because new tag EdgeGatewayType got introduced.
CI reference: https://sp-taas-vcd-butler.svc.eng.vmware.com/job/Preflight-pysdk-1.0-STF/28/console
08:37:39     raise BadRequestException(sc, request_id, objectify_response)
08:37:39 pyvcloud.vcd.exceptions.BadRequestException: Status code: 400/BAD_REQUEST, [ af8c8173-9c77-47fa-b747-28fb3ad89825 ] HTTP 400 Bad Request
08:37:39  - cvc-complex-type.2.4.b: The content of element 'Configuration' is not complete. One of '{"http://www.vmware.com/vcloud/v1.5":EdgeGatewayType}' is expected. (request id: af8c8173-9c77-47fa-b747-28fb3ad89825)
Testing Done: Executed the gateway test successfully.
@guptaankit52 @kousgy123
--- …

Jenkins Test failure fixed

---

pyvcloud/vcd/client.py
pyvcloud/vcd/platform.py
pyvcloud/vcd/vdc.py

Some of the existing code is failing flake8 check after upgrage to version 3.7.1, this change fixes them.
Testing done:
Upgraded flake8 to 3.7.1 and ran 'flake8 pyvloud/vcd'. There are no errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/403)

Fix flake8 errors after upgrade (version 3.7.1)

---

pyvcloud/vcd/gateway.py
pyvcloud/vcd/network_url_constants.py
pyvcloud/vcd/org.py
pyvcloud/vcd/vdc.py
system_tests/ipsec_vpn_test.py

[PySDK] Add IPsec VPN Sites.
This CLN contains changes related to adding VPN tunnel and test cases.
Testing Done: Added new test and executed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/404)

VP 1721: [PySDK] Add IPsec VPN Sites

---

pyvcloud/vcd/gateway_services.py
pyvcloud/vcd/ipsec_vpn.py
system_tests/ipsec_vpn_test.py

[PySDK] Delete IPsec VPN Sites
This CLN contains changes related to deleting VPN tunnel and test cases.
Testing Done: Added new test and executed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/410)

VP-1725: [PySDK] Delete IPsec VPN Sites

---

pyvcloud/vcd/gateway.py
system_tests/firewall_rule_tests.py

For editing of firewall, we need to list available object types and list of objects for every object type.
Testing Done: Added new test case and executed them successfully.
@guptaankit52 @koushik82
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/411)

[VP 1768]List objects and object types for firewall rule edit

---

pyvcloud/vcd/gateway_services.py
pyvcloud/vcd/static_route.py
system_tests/static_route_tests.py

Edit the static route on the gateway.
Following fields can be edited:
network
mtu
next hop and others.
Testing Done:
Added test case 'test_0030_update_static_routes'.
status: passed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/412)

VP-1606: Edit Static Routes

---

pyvcloud/vcd/vapp.py
system_tests/vapp_tests.py

Adding support to create a vApp network. Name and network CIDR are mandatory parameters. Optionally users can provide DNS details and IP ranges.
Testing done:
Added a test test_0110_create_vapp_network to vapp_tests.py. All test cases of this class are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/416)

[VP-1392]: Create a vApp network

---

pyvcloud/vcd/firewall_rule.py
system_tests/firewall_rule_tests.py

User can edit the service of firewall rule. Code accept list service option and modify the body accordingly and update the firewall.
Testing Done: Added services in the existing edit test case and executed them successfully.
@shashim22 @kousgy123
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/418)

 [VP-1734] Edit service of firewall rule

---

pyvcloud/vcd/firewall_rule.py
system_tests/firewall_rule_tests.py

VP-1534 : [PySDK]: Enable Firewall rule.
Adding a feature to enable/disable firewall rule on the basis of rule id.
Testing Done:
Added test_0041_enabled_firewall_rules to firewall_rule_tests.py. All test cases in this class are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/417)

VP-1534:[PySDK]: Enable Firewall rule

---

pyvcloud/vcd/gateway.py
pyvcloud/vcd/ipsec_vpn.py
system_tests/ipsec_vpn_test.py

VP-1715: [PySDK] Set Info level for logging:Global Configuration
VP-1719: [PySDK] Info Logging Settings
VP-1726: [PySDK] List IPsec VPN Sites
This CLN contains above features and their test cases.
Testing Done: Added new test case and executed them successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/419)

VP-1715,1719,1726: Set info level, info logging settings,list ipsec vpn

---

pyvcloud/vcd/gateway.py
system_tests/nat_rule_tests.py

Change the nat rule position/ sequence.
Nat rule will be moved to new position.
Testing done:
Test case 'test_0025_reorder_nat_rule' : passed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/420)

VP-1592: Change the NAT rule sequence

---

pyvcloud/vcd/firewall_rule.py
system_tests/firewall_rule_tests.py

VP-1559:[PySDK] Get Firewall rule Info..
Adding a feature to info firewall rule on the basis of rule id.
Testing Done:
Added test_0061_info_firewall_rule to firewall_rule_tests.py. All test cases in this class are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/422)

VP-1559:[PySDK] Get Firewall rule Info

---

pyvcloud/vcd/nat_rule.py

Following Changes done:
1. Convert the nat-id having lxml.objectify.IntElement to int.
2. Convert the nat-id from vcd-cli to int.
3. Handle in Pysdk when description is none
Testing done: All Nat Rule tests passed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/423)

VP-1595: Pysdk changes to handle nat-id comming from cli

---

pyvcloud/vcd/firewall_rule.py

Update test case was failing from CLI.
https://sp-taas-vcd-butler.svc.eng.vmware.com/job/Preflight-vcdcli-1.0-STF/30/consoleFull
Testing Done: Executed the firewall_rule test from CLI and PyVcloud successfully.
@shashim22 @kousgy123
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/428)

Fix of firewall rule update test case failure from CLI

---

system_tests/network_tests.py

As of now, test case is there for only sys admin execute this command. I added for orgAdmin as well.
Testing Done: Executed the network test successfully
@shashim22 @guptaankit52
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/430)

Added support for org user to convert to distributed interface

---

pyvcloud/vcd/firewall_rule.py
system_tests/firewall_rule_tests.py

VP-1789 : [PySDK] List Firewall Source.
Providing support to list firewall rule's source of rule id.
Testing Done:
Added test_0081_list_firewall_rule_source to firewall_rule_tests.py. All test cases in this class are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/437)

VP-1789 : [PySDK] List Firewall Source

---

pyvcloud/vcd/org.py

The link to share catalog was added to /api/catalog/{id}'s body in vCD api v30.0. For api versions v29.0 and below, the link lives in the body of /api/admin/catalog/{id}. The current change list takes care of this dichotomy, and makes sure that the share catalog functionality keeps working no matter what api version is specified.
Testing done :
Ran vcd-cli's vcd catalog share command with api version 29.0 and it ran successfully.
Also ran CSE 1.2.6 installation against vCD 9.0 which leverages this functionality. The installation went through.
Can't add a test in pyvcloud for this functionality because the current framework doesn't facilitate testing things from perspective of two users from two different orgs.
---
This change is [<img src="https://reviewable.io/review_button.svg" …

[VCDA-887] Fix share catalog functionality for api v29.0

---

README.md
pyvcloud/vcd/external_network.py

Updating README.md to have Python 3.6 as required version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/440)

Update required version to Python 3.6

---

requirements.txt
system_tests/main.py
system_tests/run_system_tests.sh

It will generate test report for pysdk test case run.
Testing Done: https://sp-taas-vcd-butler.svc.eng.vmware.com/view/all/job/Preflight-pysdk-1.0-STF/71/
@shashim22 @kousgy123
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/443)

Generate test reports

---

requirements.txt

Upgraded the pyyaml to 4.2b1.
https://github.com/vmware/pyvcloud/network/alert/requirements.txt/pyyaml/open
Testing Done: Executed the Gateway_test.py successfully.
@shashim22 @kousgy123
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/444)

Fix for pyyaml vulnerability found in requirements.txt

---

pyvcloud/vcd/client.py
pyvcloud/vcd/extension.py
pyvcloud/vcd/gateway.py
system_tests/gateway_tests.py

Setting of tenant syslog server IP for gateway was not available. I added this and their test case.
Testing Done: Added test case and executed the gateway_test successfully.
@pandeys
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/453)

Added code to set syslog server IP for gateway

---

pyvcloud/vcd/dhcp_binding.py
pyvcloud/vcd/gateway.py
system_tests/dhcp_binding_tests.py
system_tests/gateway_tests.py

VP-1571,VP-1849:List and Delete DHCP Binding
VP-1571: List DHCP Binding
This will list the DHCP binding of the gateway
,VP-1849:Delete DHCP Binding
Deletes the DHCP binding of the gateway
Testing : 
Done, All test cases are passing 
Added test cases in gateway_tests.py and dhcp_binding_tests.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/454)

VP-1571,VP-1849:List and Delete DHCP Binding

---

pyvcloud/vcd/gateway.py
pyvcloud/vcd/ipsec_vpn.py
system_tests/ipsec_vpn_test.py

VP-1723: [PySDK ] Edit IPsec VPN Sites
VP-1775: [PYSDK] Info VPN site
This CLN contains both functionalities and correspoding test cases.
Testing Done:
All test cases in ipsec_vpn_test class are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/455)

VP-1723,VP-1775: Update Ipsec Vpn, Info VPN site

---

system_tests/catalog_tests.py
system_tests/extnet_tests.py

Unit_Test_Failure :
Handle the test case failing for catalog and external network.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/457)

Unit_Test_Failure :

---

pyvcloud/system_test_framework/environment.py
pyvcloud/system_test_framework/vapp_constants.py
pyvcloud/vcd/client.py
pyvcloud/vcd/vapp.py
pyvcloud/vcd/vm.py
system_tests/vm_tests.py

This CL adds new methods add_nic and list_nics to vm class.
added test cases to add and list nics.
testing done: ran the newly added testcases and vcd-cli commands successfully.
note: Auto format changes are present in the CL.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/458)

VP-1797, VP-1799: vm methods: add_nic, list_nics

---

pyvcloud/vcd/vm.py
system_tests/vm_tests.py

this CL adds delete_nic method to the VM class.
added test case for the same.
testing done: ran  the test cases locally.
ran the corresponding vcd-cli command.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/459)

VP-1801: added delete_nic function to vm class.

---

pyvcloud/vcd/vdc.py

Edge gateway creation failed because position of EdgeGatewayType in Request body changed
https://sp-taas-vcd-butler.svc.eng.vmware.com/job/Preflight-pysdk-1.0-STF/82/consoleFull
Testing Done: Executed the gateway_test successfully
@shashim22 @guptaankit52
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/461)

Fix of gateway failure because of EdgeGatewayType

---

pyvcloud/vcd/utils.py

This CL adds vm_to_dict function to utils. 
This is used in vm info command to show the vm details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/460)

VP-1803: added function vm_to_dict to utils.

---

pyvcloud/vcd/vapp.py
system_tests/vapp_tests.py

VP-1901 : [PySDK] Update vApp network.
Providing support to update vapp network of vapp.
Testing Done:
Added test_0121_update_vapp_network to vapp_tests.py. All test cases in this class are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/462)

VP-1901 : [PySDK] Update vApp network

---

pyvcloud/vcd/certificate.py
pyvcloud/vcd/gateway.py
system_tests/certificate_tests.py

VP-1966: Delete service certificate
VP-1968: List all certificates
This CLN contains the above functionality and corresponding test cases.
Testing Done: Executed the certificate_tests successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/469)

VP-1966,VP-1968, list and delete service certificate

---

pyvcloud/vcd/certificate.py
pyvcloud/vcd/crl.py
pyvcloud/vcd/gateway.py
system_tests/certificate_tests.py

VP-1972: List CA certificates
VP-1976: Delete CRL certificate
Thsi CLN contains above functionality and corresponding test cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/477)

VP-1972,VP-1976:List CA and Delete CRL certificate

---

pyvcloud/vcd/client.py
pyvcloud/vcd/vm.py
system_tests/vm_tests.py

VP-2006: Suspend a VM
VP-2023: Discard suspend state
This CLN has above functionality and corresponding test cases.
Testing Done:
All test cases in the class vm_tests are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/492)

VP-2006,VP-2023: Suspend a VM and Discard suspend state

---

pyvcloud/vcd/client.py

* Added code to redact headers containing authentication info while writing them to logs
* Fixed a bug where all clients shared the same underlying logger. Say, if the first client chose not to log by writing to a null logger, subsequent loggers had no choice but to skip logging to file. As a fix only loggers writing to the same log file will share the same underlying logger.
* Added logic to create the parent directories of the log file (if missing).
Testing Done:
Tried logging in to a vCD via pyvcloud, checked the log file for the logs of corresponding REST calls. The sensitive headers had their value changed to '[REDACTED]'
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvclou …

[VCDA-926] Redact sensitive headers in log

---

pyvcloud/vcd/ipsec_vpn.py

ipsec_vpn's get_vpn_site_info test failure
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/497)

ipsec_vpn's get_vpn_site_info test failure

---

pyvcloud/system_test_framework/environment.py
pyvcloud/vcd/client.py
pyvcloud/vcd/vdc.py
system_tests/network_tests.py

VP-2183 : List network for non admin user.
Modified code for network listing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/500)

VP-2183 : List network for non admin user

---

pyvcloud/vcd/org.py

VP-2177 : Incorrect implementation of method list_rights_available_in_system in org.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/502)

VP-2177 : Incorrect implementation of method list_rights_available_in_system in org.py 

---

pyvcloud/vcd/client.py
pyvcloud/vcd/vm.py
system_tests/vm_tests.py

VP-2029: Install Vmware tools
Fix for few test cases failures.
This CLN contains above functionalities abd corresponding test cases.
Testing Done:
All test cases in class vm_tests.py are executed successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/507)

VP-2029:[PYSDK] Install Vmware tools.

---

pyvcloud/vcd/client.py
pyvcloud/vcd/vapp.py
system_tests/vapp_tests.py

VP-2098 : [PySDK] Download vapp.
Adding a support to download a vapp.
Testing done.
Added test_0056_download_ova, test_0057_download_ova to vapp_tests.py. All test cases in this class are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/506)

VP-2098 : [PySDK] Download Vapp

---

pyvcloud/system_test_framework/base_test.py
pyvcloud/system_test_framework/environment.py
pyvcloud/vcd/client.py
pyvcloud/vcd/vm.py
system_tests/base_config.yaml
system_tests/vm_tests.py

VP-2025: [PySDK]Insert CD/DVD from catalog
VP-2027: [PySDK]Eject CD/DVD
Upgrade virtual hardware
This CLN contains above functionalities and corresponding test cases.
Testing Done:
All test cases in vm_tests.py are running successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/509)

VP-2025,2027: [PYSDK]Insert and eject CD/DVD from VM

---

pyvcloud/vcd/client.py
pyvcloud/vcd/vm.py
system_tests/vm_tests.py

VP-2041: [PySDK]Consolidate VM
VP-2041: Consolidate VM
This CLN contains functionality of consolidating VM which is implemented
in method consolidate() of vm.py class. This functionality test requires
VM to be in POWERED OFF state.
Testing Done:
One test method as test_0071_consolidate() in vm_tests.py class to test
this functionality and it is getting executed successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/513)

VP-2041: [PySDK]Consolidate VM

---

system_tests/run_system_tests.sh

VP-2396: [PYSDK] Add missing test case classes to include in CI/CD.
Testing Done:
Test cases will be executed in CI/CD.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/526)

VP-2396: [PYSDK] Add missing test case classes to include in CI/CD.

---

pyvcloud/vcd/client.py

VP-2372: Fix - CI/CD of PYSDK for API version 32.0
Testing Done:
CI/CD will execute the test cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/528)

VP-2372: Fix - CI/CD of PYSDK for API version 32.0

---

pyvcloud/vcd/vapp.py
pyvcloud/vcd/vm.py
system_tests/vm_tests.py

[PySDK]Move To VM from one vapp to another
This CLN contains move operation for VM. It also contains test as
test_0073_move_to to test the new functionality.
Testing Done:
Test class vm_tests.py has test method test_0073_move_to and it is
executing successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/532)

VP-2037: [PySDK]Move To VM from one vapp to another

---

pyvcloud/vcd/vm.py
system_tests/vm_tests.py

VP-2063: [PySDK]List selected VM general properties.
This CLN contains general setting detail of VM.
general_setting_detail() methods is exposed in vm.py class and corresponding test case added.
Testing Done:
test methods test_0120_general_setting_detail() is added in test class vm_tests.py.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/546)

VP-2063: [PySDK]List selected VM general properties

---

pyvcloud/vcd/vm.py
system_tests/vm_tests.py

VP-2067: [pySDK] List Storage profiles.
This CLN contains list the storage profile of VM.
list_storage_profile() methods is exposed in vm.py class and corresponding test case added.
Testing Done:
test methods test_0130_list_storage_profile() is added in test class vm_tests.py.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/547)

VP-2067: [pySDK] List Storage profiles

---

pyvcloud/vcd/client.py

Fix flake8 issue.
@pandeys @kkkothari
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/549)

Fix flake8 issue

---

pyvcloud/vcd/client.py
pyvcloud/vcd/vm.py
system_tests/vm_tests.py

[PySDK] Check compliance
This CLN contains VM functionality to check compliance. It execute POST
REST API checkcompliance and provides the task result. Test case is
added in vm_tests.py class.
Testing Done:
Test method  test_0160_check_compliance is added in class vm_tests.py
and it is executing successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/554)

VP-2074: [PySDK] Check compliance

---

pyvcloud/vcd/vm.py
system_tests/vm_tests.py

VP-2648: [PYSDK] GET virtualHardwareSection-disks
VP-2659: [PYSDK] get virtualHardwareSection/media
VP-2662: [PYSDK] Get virtualHardwareSection/networkCards
This CLN contains above GET calls for Virtual hardware section.
Testing Done:
Test method test_0220_list_virtual_harware_section ia added in
vm_tests.py file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/567)

VP-2659,VP-2648,VP-2662: GET Virtual Hardware Section

---

pyvcloud/vcd/platform.py
pyvcloud/vcd/utils.py
pyvcloud/vcd/vdc.py
pyvcloud/vcd/vm.py
system_tests/vdc_tests.py
system_tests/vm_tests.py

VP-2076: [PySDK]Update VM nic
VP-2706: [PySDK]List media file in VDC
Changes for removing media href
This CLN contains above changes for update VM nic, list media files in
VDC and removing media href for insert and eject CD operations in VM.
Testing Done:
Test method is added in test_0080_vm_nic_operations method in
vm_tests.py file. Test method test_0070_list_media is added in
vdc_tests.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/575)

VP-2076:, VP-2709: [PySDK]Update VM nic

---

pyvcloud/vcd/client.py
pyvcloud/vcd/vm.py
system_tests/vm_tests.py

VP-2672:[PYSDK] Update OperatingSystemSection
VP-2795:[PYSDK] List Operating system section
This CLN contains list and update operating system section.
Testing Done:
Test method test_0270_list_os_info and test_0280_update_os_section added
in vm_tests.py file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/578)

VP-2672.VP-2795: List and update operating system section

---

pyvcloud/vcd/utils.py

VP-2822: [PYSDK-VCDCLI] Bug fixes of CI/CD
This CLN contains fix for failure in Org and Gateway test cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/587)

VP-2822: [PYSDK-VCDCLI] Bug fixes of CI/CD

---

pyvcloud/vcd/client.py
pyvcloud/vcd/vm.py

Add `mac_address` to dict produced by vm.list_nics() method
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/480)

Add mac_address to VM NIC listing

---

pyvcloud/vcd/client.py
pyvcloud/vcd/vm.py
system_tests/vm_tests.py

VP-2644:[PYSDK] screen:acquireTicket
VP-2646:[PYSDK]screen:acquireMksTicket
VP-2627:[PYSDK] get product section
VP-2639:[PYSDK] Screen:thumbnail
This CLN contains above VM operations
Testing Done:
Test methods test_0410_list_screen_ticket,test_0420_list_mks_ticket and
test_0430_list_product_sections are added in vm_tests.py file
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/597)

VP-2644,VP-2646,VP-2627,VP-2639 ticket and product section operations

---

system_tests/vm_tests.py

Fix for VM relocate test case failure
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/599)

Fix for VM relocate test case failure

---

pyvcloud/vcd/vapp.py
system_tests/vapp_tests.py

VP-2005: [PySDK]As a SDK user, I can create VM from scratch.
This CLN contains create VM from scratch.  
add_vm_from_scratch() method is exposed in vapp.py class and corresponding test case added.  
test_0250_add_vm_from_scratch() is added in test class vapp_tests.py.  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/600)

VP-2005: [PySDK]As a SDK user, I can create VM from scratch.

---

pyvcloud/vcd/vdc.py
pyvcloud/vcd/vm.py
system_tests/vdc_tests.py
system_tests/vm_tests.py

VP-2704:[PySDK]List Independent disk in VDC
VP-2884:[PYSDK] enableNestedHypervisor
This CLN contains List independent disk in VDC and enable nested
hypervisor of VM operations.
Testing Done:
Test method test_0080_list_idisk is added in vdc_tests.py and
test_0450_enable_nested_hypervisor is added in vm_tests.py file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/603)

VP-2704,VP-2884: List Independent diks, enable nested hypervisor

---

system_tests/vdc_tests.py

VP-2917: [PYSDK] bug fix for list_idisk CI/CD failure.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/604)

VP-2917: [PYSDK] bug fix for list_idisk CI/CD failure.

---

system_tests/extnet_tests.py
system_tests/network_tests.py

Commemnting test cases whcih are affected with PR:2399981 and 2399911
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/609)

Commenting PR raised test cases

---

pyvcloud/vcd/org.py
system_tests/vdc_tests.py

VP-2981: get_vdc issue with PySDK
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/611)

VP-2981: get_vdc issue with PySDK

---

pyvcloud/vcd/vdc.py

VP-3104 : Unable to delete Vapp Due to pagination in VDC
Testing done
vapp_tests and vm_test had passed all test cases.
Manually tested and working fine.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/623)

VP-3104 : Unable to delete Vapp Due to pagination in VDC

---

README.md

- Adding supported API versions in README
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/641)

Adding supported API versions in README

---

AUTHORS
ChangeLog
pyvcloud/vcd/utils.py
pyvcloud/vcd/vapp.py
system_tests/vapp_tests.py

This PR includes following changes,
1. It updates an entire approach to add a new disk
to a VM with specified DISK_CONTROLLER
2. It adds approapriate tests to validate
disk addition functionality with DISK_CONTROLLER
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/648)

Fix Not able to add a new disk to a VM #647

---

pyvcloud/vcd/vm.py

The following commit allows updating a VM nic as a primary nic.
Resolved: #656
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/657)

Fixed - Updating a VM nic as primary nic

---

pyvcloud/vcd/vapp.py

This commit does following,
1. It adds an `if` condition to check whether
`ip_ranges` is not `None` before iterating
in `create_vapp_network`
Resolved: #658
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/659)

Updates `create_vapp_network` to check `ip_ranges` before using

---

pyvcloud/vcd/org.py
pyvcloud/vcd/utils.py
pyvcloud/vcd/vapp.py

- add sizing policy based on api version to spec for adding vms to vapp
- modify to_sourced_item() to include sizing policy in spec
@rocknes @andrew-ni @sakthisunda @sahithi 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/662)

Added sizing policy to vapp.add_vm()

---

pyvcloud/vcd/vm.py

This commit adds str() and int() function to
convert vm disk's properties of lxml elements
into respective data values
Resolved: #678
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/679)

Update VM's list_virtual_hardware_section()

---

pyvcloud/vcd/org.py
pyvcloud/vcd/utils.py
pyvcloud/vcd/vm.py

- Update compute policies for a VM should support updating and removing placement policies as well.
- Testing done: Update sizing and placement policy for existing VMs.
- @rocknes @sakthisunda @andrew-ni @sahithi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/674)

Update placement policy for vms

---

pyvcloud/vcd/vm.py

This commit add a `nic_id` argument to `update_nic`
method of vm.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/685)

Proposal to update a specific vm nic attached with a network

---

pyvcloud/vcd/org.py
system_tests/vcd_user.py

This commit updates  `update_user` method
to update the org user method. It also adds
a respective test to validate the functionality
Resolved: #686
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/697)

Updating Org user password

---

pyvcloud/vcd/client.py

* Log timestamps along with the log message.
* Split request sent and response received logs to better track how long vCD took to serve a request.
Testing done:
Ran all CSE workflows that use pyvcloud and checked the logs for presence of the timestamps
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/707)

Improve logging in pyvcloud

---

pyvcloud/vcd/vm.py
system_tests/vm_tests.py

This commit cast the nic index text as integer
Resolved: #706
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/708)

Listing nics with integer index values

---

pyvcloud/vcd/client.py

vCD zeus will no longer accept double encoded filter value as part of query api.
To accommodate the shift in behavior, pyvcloud will no longer double encode the query filter string and won't send in the filterEncoded param either for api v35.0+.
However the values in qfilter param to get_typed_query should still be encoded, the responsibility lies with the caller. However the equality_filter's value will be encoded by pyvcloud.
Testing done:
Ran the following command from vcd-cli with three different version of pyvcloud and verified that all of them are working
10.0.0.3
--------
pyvcloud 21.0.0 - api v33.0
vcd role info "Organization Administrator" -o cseorg
https://[REDACTED]/api/query?type=adminRole&format=records&page=1&filterEncoded=true&filter=org%3D%3Dhttps%253A%252F%252F[REDACTED]%2 …

For api 35.0+, single encode query filter, and remove filterEncoded param

---

README.md

- Update README file to reflect supported vCloud versions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/721)

Update supported version in README

---

pyvcloud/vcd/org.py
system_tests/vdc_tests.py

This commit adds the following,
1. a new method `update_org_vdc` to update an org VDC.
2. respective test to validate the method
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/727)

Update an Org VDC

---

pyvcloud/vcd/client.py

Add support to Abstract Query to return a single page response
Testing done:
Called the newly created function from CSE to get paginated response
Tested with invalid page number and pageSize (non existent page and negative values for page and pageSize)
@rocknes @sahithi @sakthisunda @ltimothy7 @ChintanShahVMware
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/724)

Query to get a single page response

---

pyvcloud/vcd/client.py

- Add support for API version 36 in pyvcloud
Testing done:
1. Run and install CSE with new API version
@rocknes @sakthisunda @ChintanShahVMware @ltimothy7 @arunmk @sahithi @andrew-ni
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/734)

Add support for API version 36 in pyvcloud

---

pyvcloud/vcd/org.py

Remove the following fields while making POST /api/admin/org/{id}/users
* E.IsAlertEnabled(is_alert_enabled),
* E.AlertEmailPrefix(alert_email_prefix),
* E.AlertEmail(alert_email),
* E.IsDefaultCached(is_default_cached)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/735)

Remove deprecated fields from UserType XML payload while creating a new user.

---

pyvcloud/vcd/vdc_network.py

Signed-off-by: ltimothy <ltimothy@vmware.com>
vdc network can detect if it is a routed network
Tested this helper function with a routed and a direct network, and the function correctly detects if the network is routed. 
@rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/738)

[VCDA-2006] added function to detect vdc network is routed

---

pyvcloud/vcd/gateway.py

Signed-off-by: ltimothy <ltimothy@vmware.com>
- Added a helper to check if the gateway is NSX-T backed.
Tested this on an NSX-T backed gateway.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/740)

added nsxt backed helper

---

pyvcloud/vcd/gateway.py

Signed-off-by: ltimothy <ltimothy@vmware.com>
- Updated gateway check for is_nsxt_backed
Checked for correctly identifying NSX-T backed gateway.
@Anirudh9794 @rocknes @sakthisunda
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/750)

safer check for checking gateway is nsxt backed

---

pyvcloud/vcd/nsxt_extension.py

Adding a new module NsxtExtension to add/update/delete NSX-T Manager
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/764)

Adding a new extension module to connect NSX-T Manager with VCD

---

pyvcloud/vcd/vm.py

This commit updates the vm nic error
message in case of missing network name
Resolved: #770
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/771)

Update VM nic update error message

---

pyvcloud/vcd/client.py

Added version objects enum.
@rocknes @sakthisunda
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/779)

[VCDA-2669] Add version objects enum

---

pyvcloud/vcd/client.py

Signed-off-by: ltimothy7 <66969084+ltimothy7@users.noreply.github.com>
This PR allows accessing the AlphaVersion field of versions safely and parses the alpha api version to remove the build number
@sahithi @sakthisunda
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/797)

[VCDA-3862] safe access for AlphaVersion
