- pyvcloud/vapp.py
When setup custom admin password, fields PasswordAuto and ResetPasswordRequired must be  "False"
> Fix error in customize_guest_os, when setup admin password

- pyvcloud/vapp.py
- pyvcloud/vcloudair.py
The old version of function _create_instantiateVAppTemplateParams() uses SourcedVmInstantiationParamsType  for customization cpu and memory.
SourcedCompositionItemParamType and SourcedVmInstantiationParamsType 	can't be presents together.
If SourcedCompositionItemParamType section is present, then SourcedVmInstantiationParamsTypesection (if present) will be ignored. 
But customizing vm_name uses SourcedCompositionItemParamType.
Also InstantiateVmHardwareCustomizationParamsType is deprecated since v.5.6.
Also fix error in get_vms_details()
> Fix bug, with configure cpus and memory during creating vapp.

- pyvcloud/vapp.py
- requirements.txt
Some dependencies are only useful for vca-cli, this cleans the requirements.txt (and an unused import)
PyYAML, tabulate and xmltodict should be moved to vca-cli dependencies
I could not find any use in vca for wsgiref but maybe missed it
> Clean requirements

- pyvcloud/vcloudair.py
- pyvcloud/vcloudsession.py
Instead of manually creating the basic auth header, this uses requests' module
I had to track that one down as I had a netrc file in my profile, and this overrides manually set headers (getting me 401 answers hard to understand at first) 
(tested on vloud director only, but the logic is the same for vcloud air)
> Use requests' HTTPBasicAuth for authentication

- pyvcloud/schema/vcd/v1_5/schemas/vcloud/vcloudType.py
- pyvcloud/vcloudair.py
For users who are on API version 5.5 there is an issue when using create_vapp and having a vm_name set.
The 5.5 API doesn't like the ```<SourcedItem>``` tag with VmGeneralParams and as a result will respond with an Error as it is not part of the 5.5 API
The resolution is to set the SourcedItem = None and not setting any vcloudType.VmGeneralParamsType parameters since the VmGeneralParamsType was not added to the API until 5.6  (Reference: http://pubs.vmware.com/vca/index.jsp?topic=%2Fcom.vmware.vcloud.api.reference.doc_56%2Fdiff%2Flanding-all_types_diff.html)
And since we want to change a name, we can set the templateParams.set_name function to be the vm_name
Its not the perfect solution but it will help those who are on 5.5
> Fixes Issue #41 for users who are using vCloud Director API version 5.5

- pyvcloud/score.py
Revert casting from boolean to strings.
Score expects to have booleans instead of sting during install executions.
> Revert casting from boolean to strings

- pyvcloud/score.py
Force blueprint upload method to check blueprint.
This change prevents from bothering Score to run
simple validation, i.e valid YAML syntax, absence of imports, etc.
> Validate blueprint before upload

- pyvcloud/score.py
- requirements.txt
dsl_parser uses only with score service, but score service package already has dsl_parser module in requirements.
> Import cloudify-dsl-parser only when validation required.

- pyvcloud/vapp.py
- pyvcloud/vcloudair.py
- pyvcloud/vcloudsession.py
Symptoms: when logging in to a standalone instance (vCloud 5.6), user
gets the following error message:
'''
Can't login: The request has invalid accept header. Supported API
versions are: [1.5, 5.1, 5.5, 5.6]
'''
It is because the get_service_type returns wrong value.
Because the standalone instance (vCloud 5.6) returns code 406 for
end point /api/iam/login. So the get_service_type return vca instead
standalone.
This fix just quick patch to work with standalone instance. However, the
status_code checking for VCA should be similar to VCHS a few lines
below. (maybe check if the return code is 401?). I'll leave it to someone
more familiar with VCA to change it.
> Fix this issue unable to login to a standalone instance

- pyvcloud/vcloudair.py
Status code 404 results in incorrect VCD identification as VCA. The correct status code returned by VCD is 406 (Not acceptable).
> Fixing service type identification for VCD

- pyvcloud/vcloudair.py
`get_service_type` cannot detect standalone vCD, because vCD 8.0 returns `403 Forbidden` error when requesting to `https://<vcd_host>/api/iam/login`.
> Fix get_service_type cannot detect standalone vCD

- pyvcloud/vapp.py
- pyvcloud/vcloudair.py
Since API version 5.6 allows a single virtual machine (VM) to access different tiers of storage, this patch will allow for the selection of a storage profile when creating an independent disk.
I have modified add_disk to accept the following additional parameters :
- bus_type to define a specific Disk.busType
- bus_sub_type to define a specific Disk.busSubType
- comment that will be visible in the disk details
- storage_profile_name to define a specific storage profile for that disk (must be in the allowed storage profile defined for the vDC)
> Added options to select storage profile, bus type and add comment when creating an independent disk

- pyvcloud/vapp.py
- pyvcloud/vcloudair.py
- tests/vcloud_tests.py
This pull request adds the following features/fixes:
* Ability to specify guest customization settings during vAPP composition.
* Specifying names of the vms using the Source ReferenceType during vAPP composition. This enables naming the vms in versions <=5.5.
* Is_connected option to specify if vm nic should be connected.
* Ability to deploy specific vm from a template that includes multiple.
* ID field to get_vms_details.
* Fix hdd_capacity in get_vms_details.
* Updated tests.
> Add guest customization

- pyvcloud/vcd/client.py
- pyvcloud/vcd/org.py
- pyvcloud/vcd/utils.py
- tests/vcd_catalog.py
(pyvcloud) malakars-m01:pyvcloud malakars$ pwd
/Users/malakars/pyworkspace/pyvcloud
(pyvcloud) malakars-m01:pyvcloud malakars$ cd tests
(pyvcloud) malakars-m01:tests malakars$ python -m unittest vcd_catalog.TestCatalog.test_catalog_control_access_retrieval
/Users/malakars/.virtualenvs/pyvcloud/lib/python3.6/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
InsecureRequestWarning)
.
Ran 1 test in 0.435s
OK
> VCDA-217: Retrieve access control settings of a catalog

- pyvcloud/vcd/cluster.py
Testing done :
CLI command :
(vcd-cli) C:\code\vcd-cli>vcd cluster create -n net1 -N 2 -c 2 -m 1025 --ssh-key ssh-key.txt "aritra-test-cluster"
cse.log :
DEBUG    2017-11-29 08:14:08,615 container_service_extension.processor    process_request                      55  : request body: {"name": "aritra-test-cluster", "node_count": 2, "vdc": "vdc1", "cpu-count": "2", "memory": "1025", "network": "net1", "storage_profile": null, "ssh-key": "sample SSH key"}
Note : the command failed with an error stating 'not enough IP addresses' on the extension. But I believe it's not related to my changes.
> Adding new params to create_cluster function

- pyvcloud/vcd/vdc.py
Testing done :
(vcd-cli) C:\code\vcd-cli>vcd disk list
id                                    name    size        size_bytes  status
------------------------------------  ------  --------  ------------  --------
477fe6a5-1fc8-4bf9-b54b-2a7a7849b775  disk1   20 bytes            20  Resolved
b714176a-9c72-48df-9017-c73550e7bee0  disk1   10 bytes            10  Resolved
(vcd-cli) C:\code\vcd-cli>vcd disk delete disk1
Are you sure you want to delete the disk? [y/N]: y
Usage: vcd disk delete [OPTIONS] <name>
Error: Found multiple disks with name disk1, please specify disk id along with disk name.
(vcd-cli) C:\code\vcd-cli>vcd disk delete disk11234
Are you sure you want to delete the disk? [y/N]: y
Usage: vcd disk delete [OPTIONS] <name>
Error: No disk found with the given name/id.
(vcd-cli) …
> get_disk(name, id) now alerts users if there are multiple namesake disks

- pyvcloud/vcd/utils.py
- test-requirements.txt
Tested the following scenarios
Environment variable USE_COLORED_OUPUT not set
------------------------------------------------------
vcd info catalog 87d6f1f7-6d29-4abc-9f09-ce8322175901 : Colored output
vcd --colorized info catalog 87d6f1f7-6d29-4abc-9f09-ce8322175901 : Colored output
vcd --no-colorized info catalog 87d6f1f7-6d29-4abc-9f09-ce8322175901 : Monochrome output
Environment variable USE_COLORED_OUPUT is set to 0
------------------------------------------------------
vcd info catalog 87d6f1f7-6d29-4abc-9f09-ce8322175901 :  Monochrome output
vcd --colorized info catalog 87d6f1f7-6d29-4abc-9f09-ce8322175901 : Colored output
vcd --no-colorized info catalog 87d6f1f7-6d29-4abc-9f09-ce8322175901 : Monochrome output
Environment variable USE_COLORED_OUPUT is set to 1 …
> Introducing capability to print xml in monochrome

- CODE_OF_CONDUCT.md
- ISSUE_REQUEST.md
- PULL_REQUEST_TEMPLATE.md
Added files to fulfill GitHub community standards.  Code of conduct
adapted from VMware Clarity project.  PR and issue conventions are
derived from current practice.
> Add code of conduct and PR/issue templates

- pyvcloud/vcd/vdc.py
- tests/vcd_network.py
Adding capability to create isolated OrgVDC networks.
* Added a new function create_isolated_vdc_network() in vdc.py which can be used to create isolated org vdc networks,
* Added unit test for the same
* Ran yapf on vdc.py and vcd_network.py (P.s. pull request will contain few style changes in functions unrelated  to the current feature).
Unit test result :
(pyvcloud) C:\code\pyvcloud\tests>python -m unittest vcd_network.TestNetwork.test_020_create_isolated_orgvdc_network
.
Ran 1 test in 64.571s
OK
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/171)
> VCDA-369: Adding capability to create isolated OrgVDC networks.

- pyvcloud/vcd/vdc.py
Root cause : Due to an extra level of indentation, the loop that collected all the storage profiles was getting terminated earlier than expected.
Fix : Remove the extra indentation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/181)
> Issue#142: Fixed bug in vdc.py : get_storage_profiles() that was returning only first storage profile.

- pyvcloud/vcd/client.py
- pyvcloud/vcd/vdc.py
- tests/vcd_network.py
* Added functionality to get all org vdc network records
* Added functionality to get org vdc network resource, filtered by name and type
* Added functionality to delete org vdc networks by name
* Unit tests for implemented features
* Minor text fixes
Unit test output
---------------------
(pyvcloud) C:\code\pyvcloud\tests>python -m unittest vcd_network.TestNetwork
.......
Ran 7 tests in 117.558s
OK
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/184)
> VCDA-395 and VCDA-396: Add support for listing and deleting org vdc networks

- pyvcloud/vcd/vapp.py
- pyvcloud/vcd/vm.py
- tests/vcd_vapp_vm.py
- tests/vcd_vm.py
Includes SDK methods for rebooting and shutting down a vapp or VM(s) within a vapp
Added SDK methods for rebooting a vApp/VM
Added SDK methods for shutting down a vApp/VM
Added required unit tests.
**Command** : **vcd vapp shutdown sompa-vapp**
```
Are you sure you want to shutdown the vApp? [y/N]: y
vappShutdownGuest: Shutting down Virtual Application sompa-vapp(e332aacb-9a80-4aed-860c-af7de0ca10e9)
vappShutdownGuest: Shutting down Virtual Application sompa-vapp(e332aacb-9a80-4aed-860c-af7de0ca10e9)
task: 0df63085-0b7a-4bf4-9c46-203d2979655e, Shut down Virtual Application sompa-vapp(e332aacb-9a80-4aed-860c-af7de0ca10e9), result: success
```
**Command:** **vcd vapp shutdown sompa-vapp vm3**
```
Are you sure you want to shutdown the vApp? [y/N]: y
vappShutdownGuest: Shutting down Virtual …
```
> VCDA-365,366: Shutdown and Reboot a vapp/VM

- pyvcloud/vcd/vdc.py
Added check to make sure that we try to iterate over EdgeGatewayRecord only if there is atleast one of them.
Ran vcd-cli command vcd gateway list to make sure that no errors were thrown on a system with 0 edge gateways.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/192)
> VCDA-471: Fixed listing of edge gateways, when there are none in the system

- pyvcloud/vcd/platform.py
- tests/vcd_vc.py
* Modified get_vcenter() to raise exception if a suitable vCenter is not found
* Added unit test
(pyvcloud) C:\code\pyvcloud\tests>python -m unittest vcd_vc.TestVC.test_0003_get_vc_negative
.
Ran 1 test in 1.233s
OK
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/193)
> VCDA-472: get_vcenter() in platform.py should raise exception when a vCenter with the user provided name can't be found.

- pyvcloud/vcd/client.py
vCD is case insensitive when it comes to organization names and user names. We are mimicing the behavior in pyvcloud.
* Made the system org check case insensitive for set_crendentials(), rehydrate(), rehydrate_from_token()
* get_org_by_name is now case insensitive to organization name
n.b. user name related operations are already case insensitive, thanks to the use of query service to fetch user resource/reference/record by name.
To test the fallout of these changes, the following commands were invoked from vcd-cli
1. vcd org info
2. vcd org use
3. vcd org list
4. vcd org update
5. vcd org delete
All of them worked fine and displayed case insensitiveness towards org name and username
--- …
> VCDA-370: Functions dealing with org name and user name are now case insensitive

- pyvcloud/vcd/vapp.py
- pyvcloud/vcd/vdc.py
- tests/vcd_vapp.py
```
C:\sources\github\service_ecosystem\vcd-cli (master)
(vcd-cli) λ vcd vapp disconnect v1 ovdcnet
Are you sure you want to disconnect the network? [y/N]: y
Successfully disconnected ovdc network 'ovdcnet' from vapp 'v1'
C:\sources\github\service_ecosystem\vcd-cli (master)
(vcd-cli) λ vcd vapp disconnect v1 ovdcneter
Are you sure you want to disconnect the network? [y/N]: y
Usage: vcd vapp disconnect [OPTIONS] <vapp-name> <orgvdc-network-name>
Error: Orgvdc network 'ovdcneter' is not attached to the vapp
C:\sources\github\service_ecosystem\vcd-cli (master)
(vcd-cli) λ vcd vapp connect v1 ovdcneter
Usage: vcd vapp connect [OPTIONS] <vapp-name> <orgvdc-network-name>
Error: Orgvdc network 'ovdcneter' does not exist in vdc 'vdc1'
C:\sources\github\service_ecosystem\vcd-cli (master)
(vcd-cli) …
```
> VCDA-421 & VCDA-422: Implementing SDK methods and cli commands to connect/disconnect ovdc_network to/from vapp.

- pyvcloud/vcd/org.py
- pyvcloud/vcd/pvdc.py
- pyvcloud/vcd/role.py
- pyvcloud/vcd/system.py
- pyvcloud/vcd/vapp.py
- pyvcloud/vcd/vdc.py
- pyvcloud/vcd/vm.py
Currently, all pyvcloud Entity constructors expect one of href and resource variables to be populated. When both href and resource arguments are None, it fails at vCD rest-api calls instead of failing at pyvcloud level.
This change-set ensure that all constructors raise exception when both href and resource are found to be None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/196)
> VCDA-397: Refactor constructors to raise Error when both href and resource are None.

- examples/tenant-onboard.py
- examples/tenant-remove.py
- examples/tenant.yaml
- examples/tenantlib.py
Created a sample script tenant-onboard.py that reads org information
from a .yaml configuration and then creates everything it finds in vCD.
If run again, the script creates anything missing and leaves existing
entities alone. Script tenant-remove.py removes the org. Sample org
information is included in tenant.yaml.
@pacogomez, @sahithi, @anusuyar
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/202)
> VCDA-495: Add a sample application to illustrate on-boarding

- docs/install.md
Added latest information on setting Python path as well as updating pbr
to ensure pip3 install works.
Reviewers: @sompa, @sahithi, @rocknes, @anusuyar
> VCDA-502: Add additional Mac OS X install notes

- examples/list-vapps.py
The example script is `list-vapps` but it was listing **all** resources in the VDC. This commit limits the resources fetched and displayed to only those with entity type 'vApp' (aka `EntityType.VAPP`).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/218)
> Only show VAPP entity types, per intention of example

- pyvcloud/vcd/client.py
- pyvcloud/vcd/vdc.py
This supports deploying a VM from template with static manual ip allocation mode and enables support to set network adapter type from vdc.instantiate_vapp method
Signed-off-by: Greg Westerfield <gwesterfield@vmware.com>
Signed-off-by: Greg Westerfield <gwesterfieldjr@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/226)
> #205 Deploying VM's with manual allocation mode

- pyvcloud/vcd/org.py
Updating documentation of org:create_user() to reflect a subtle restriction on the 'password' param string.
Testing : not required.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/237)
> Updating documentation of org:create_user()

- pyvcloud/vcd/utils.py
- pyvcloud/vcd/vdc.py
* Added an extra param to vapp_instantiate() to take in description of the vApp
* Also replaced handcrafted url to create vApp to linked url.
Tested the feature manually using vcd-cli to verify that the new vApp has the user provided description.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/238)
> Added an extra param to vapp_instantiate() to take in description of vApp

- pyvcloud/vcd/client.py
- system_tests/README.md
- system_tests/search_tests.py
Fixed KeyError that appears if you search for an entity type that has
no corresponding entities. Added docstring to Client.get_typed_query
method to make it clearer what arguments do. Implemented system test for
search to verify fix as well common search API usage.  Updated README.md
in system_tests directory to explain how to develop new tests.
(This arose in vcd-cli testing, hence the reference to a vcd-cli issue.)
Reviewers: @ckolovson, @rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/245)
> vcd-cli 210: Fixed KeyError and added system test for search

- pyvcloud/system_test_framework/base_test.py
- pyvcloud/system_test_framework/environment.py
- pyvcloud/vcd/client.py
- pyvcloud/vcd/test.py
- system_tests/client_tests.py
- system_tests/run_system_tests.sh
Adapted Client class to default to highest API version supported by
pyvcloud and negotiation down to a lower certified vCD API version if
necessary.  Restricted pyvcloud certified versions to vCD 8.20 up to
vCD 9.1 (current prod release).  Added method to get client version 
in effect and cleaned up selection of highest server version. 
Implemented client system test to check login and API versioning
behavior, added precise documentation for APIs related to login/logout,
and eliminated client socket leaks due to login failures.  Added new
client system test to stable test list in run_system_tests.sh.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/248)
> VCDA-635: Implement pyvcloud client to server API version compatibility

- pyvcloud/system_test_framework/environment.py
- system_tests/catalog_tests.py
- system_tests/cleanup_test.py
- system_tests/client_tests.py
- system_tests/idisk_tests.py
- system_tests/nsxt_tests.py
- system_tests/run_system_tests.sh
- system_tests/search_tests.py
- system_tests/vapp_tests.py
* Fixed catalog sharing issue in system tests. Now users other than catalog author can access the test catalog.
* Tests in idisk_tests.py and vapp_tests.py now now run in VAPP_AUTHOR context.
* System Admin client is no longer a singleton. Each call to get_sys_admin_client() will now generate a new client. Added fallout code to logout the aforementioned client in various test suites.
* Fixed documentation in system tests.
* Fixed flake8 errors in search, client and cleanup tests.
Ran all the tests
(pyvcloud) C:\code\pyvcloud\system_tests>python -m unittest idisk_tests.py client_tests.py vapp_tests.py catalog_tests.py cleanup_test.py -v
All of them succeeded.
--- …
> [VCDA-603] Catalog sharing fix for system tests,

- pyvcloud/vcd/org.py
vCD 9.0 and vCD 9.5 behave differently when the following api call is made to them using api v29.0.
/api/catalog/{id}
vCD 9.0 doesn't return the "remove" link, while vCD 9.5 does. Our implementation of Org.delete_catalog() depends on the link. As a result all catalog delete operations were failing against vCD 9.0.
As a fix we have now moved to the admin version of the href for delete operations.
/ap/admin/catalog/{id}
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/259)
> Fixed catalog delete operation for vCD 9.0.

- pyvcloud/system_test_framework/environment.py
- pyvcloud/vcd/client.py
- pyvcloud/vcd/system.py
- pyvcloud/vcd/utils.py
- system_tests/catalog_tests.py
- system_tests/cleanup_test.py
- system_tests/idisk_tests.py
- system_tests/org_tests.py
- system_tests/vapp_tests.py
* Added Org system tests.
* Added proper license header to all the system test files.
* Standardized Client.get_org_by_name() and Client.get_org_list() method's output format
* Handled fallout of the changes to Client.get_org_by_name() and Client.get_org_list()'s output.
* Fixed a bug in Utils.get_admin_href() and Utils.get_admin_extension_href() to make them idempotent.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/258)
> [VDCA-584] Added Org system tests

- pyvcloud/vcd/platform.py
When no vCenter servers are attached to vCD, attempt to invoke list_vcenters() function in platform.py will fail.
E.g.
(vcd-cli) C:\code\vcd-cli>vcd vc list
Usage: vcd vc list [OPTIONS]
Error: no such child: {http://www.vmware.com/vcloud/extension/v1.5}VimServerReference
Added guard code to avoid looking for the non-existent XML tags while looking for vCenter server references.
After fix,
(vcd-cli) C:\code\vcd-cli>vcd vc list
(vcd-cli) C:\code\vcd-cli>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/262)
> [vcd-cli Issue 228] Added guard code to handle cases in list_vcenters() when vCD isn't connected to any vCenter.

- pyvcloud/vcd/org.py
- pyvcloud/vcd/utils.py
Issue : https://docs.python.org/3/library/tarfile.html#tarfile.TarFile.extractall
Fix is outlined at https://stackoverflow.com/questions/10060069/safely-extract-zip-or-tar-using-python/10077309#10077309
tarfile.extractall() method doesn't check for the presence of directory meta info hidden in file names of the archive members. As a result, malicious tar files can be used to extract payload into directories other than the target directory.
As a fix we filter out non safe members of archives before extracting them.
Testing Done:
1. Created an archive containing a file named "\\..\\1.txt". If this archive is extracted on windows, it will extract the text file in the root directory.
2. Wrote a a sample script to extract this tarfile with and without the filter we wrote.
Without filter : File …
> [VCDA-707] Fixed security hole in tarfile.extractall() related to directory walking.

- pyvcloud/system_test_framework/base_test.py
- pyvcloud/vcd/test.py
- requirements.txt
Fix  for CVE-2017-18342 http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-18342
Restricted dependency on PyYAML to >=3.10 and <=3.13
Replaced instances of yaml.load() to yaml.safe_load()
Pulled a fresh copy of pyvcloud from github and checked,
1. Correct version of PyYAML is being installed as part of setup
2. Ran all pyvcloud system tests to make sure that the yaml.safe_load() didn't cause any regressions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/266)
> [VCDA-708] CVE-2017-18342 : Replace yaml.load() with yaml.safe_load()

- pyvcloud/system_test_framework/base_test.py
- pyvcloud/system_test_framework/environment.py
- pyvcloud/system_test_framework/utils.py
- system_tests/idisk_tests.py
- system_tests/vm_tests.py
* Removed default vApp and vm creation steps from base test
* Made changes in idisk_tests.py to adjust to the removal of default vApp and vm in the test vdc.
Ran independent disk test suite to make sure no regression crept in , all tests ran successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/281)
> [VCDA-736] Remove creation of default vapp and vm from base test.

- pyvcloud/vcd/api_extension.py
- pyvcloud/vcd/client.py
- pyvcloud/vcd/org.py
- pyvcloud/vcd/platform.py
- pyvcloud/vcd/system.py
- pyvcloud/vcd/task.py
- pyvcloud/vcd/utils.py
- pyvcloud/vcd/vdc.py
The core issue in this case was that the filter value in the query uri wasn't being uri encoded properly.
We were encoding the individual filter sub expression values, but leaving out encoding the whole filter params value.
Have made changes in the code, to make sure that,
1. all values in the qfilter param are properly uri encoded.
2. the value in equality_filter tuple is properly uri encoded.
3. the final filter param value is properly encoded.
Also did some cleanup of the code
* Replaced hard coded resource type  strings with their ResourceType enum counterparts.
* Removed dead code related to python 2.
Ran the following tests,
api_extension_tests, catalog_tests, cleanup_test, client_tests, idisk_tests, network_tests, org_tests, vapp_tests, vc_tests, vdc_tests
All test passed.
---
This …
> [VCDA-549] Fix query service in pyvcloud to accomodate filtering names with commas

- pyvcloud/system_test_framework/environment.py
- pyvcloud/system_test_framework/utils.py
- pyvcloud/vcd/client.py
- pyvcloud/vcd/vapp.py
- pyvcloud/vcd/vdc.py
- system_tests/network_tests.py
- system_tests/vm_tests.py
For api version <=29.0, and non admin users, response to GET /api/query doesn't have the link to the typed query OrgVdcNetwork. This restricts those users from performing actions like attach an orgvdc network to a vApp. To solve this issue we will use the typed query OrgNetwork instead of OrgVdcNetwork, if the user in question is not an admin and the api version used is <=29.0.
Ran all system tests against
1. vCD 9.5 at api version 29.0 and api v31.0.
2. vCD 9.0 at api version 29.0.
Confirmed that all tests pass and the workflows in question have been unlocked for non admin users.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/284)
> [VCDA-750] Restore access to org vdc network related workflows for non admin users while using api version <= 29.0

- pyvcloud/vcd/api_extension.py
- pyvcloud/vcd/client.py
- system_tests/search_tests.py
Whenever a typed query with an invalid type value or a type value that is hidden from the current user is specified, pyvcloud is unable to construct the query url and chooses to silently return an empty list as result set. This change list changes the behavior to raise an OperationNotSupportedException, as well as log the issue in log file.
As a fallout search_tests needed to be modified to address this behavioral change.
Also fixed a small typo in one of the Type Query type values (these type values are case sensitive).
Testing done : Ran all system tests and verified that none of them are failing after this change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/288)
> [VCDA-762] Invalid Query will raise OperationNotSupportedException instead of silently returning empty list as result.

- requirements.txt
Updated requirements.txt to bump up version of lxml module to 4.2.1.  The older version of lxml has dependency on Microsoft Visual C++ runtime which cause installation failure on Windows machines.
Tested on Windows, Linux, Mac and made sure that installation + commands work fine on these systems.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/290)
> [VCDA-756] Update version of lxml to 4.2.1 to avoid failure during installation on Windows machines

- pyvcloud/vcd/api_extension.py
The param 'patterns' is not a string but a list. Updated the document accordingly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/296)
> Fix documentation for method add_extension in module api_extension.py

- system_tests/search_tests.py
With https://github.com/vmware/pyvcloud/pull/288 the behavior of query service has changed. Queries with invalid query type will now generate OperationNotSupoprtedException. This also means that the search_tests needs to be adjusted to take in account the new behavior. In the earlier pull request we missed the broken test cases for api version 29.0 and lower. This PR fixes them by adjusting the expected behavior correctly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/295)
> Fix search test for api version <= 29.0

- examples/tenant-onboard.py
- examples/tenant-remove.py
yaml.load() can be used by an attacker to  execute arbitrary code, yaml.safe_load() is capable of stopping this exploit. In this PR we have replaced all occurrences of yaml.load() with yaml.safe_load() in the sample pyvcloud app.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/299)
> Change occurrence of yaml.load() to yaml.safe_load() in examples

- pyvcloud/vcd/org.py
While uploading a template to a catalog we make multiple PUT calls in succession and write the data bits on the server. However while making the PUT calls we are specifying the wrong range where the data should be written. This can cause vCD to forcibly close the TCP connection, which will eventually lead to failed uploads.
This changelist fixes the value we are sending in Content-Range header of these PUT calls.
Signed by: Aritra Sen <aritra.iitkgp@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/303)
> [VCDA-786] Fix failure during template uploads to catalog.

- pyvcloud/vcd/client.py
- pyvcloud/vcd/org.py
This PR is addendum to https://github.com/vmware/pyvcloud/pull/303
If vCD servers are behind a load balancer, the TCP connections are generally closed as soon as the first response is sent out by the load balancer. If we pump too much data in a short burst to such a system, we run the risk of getting back 416 instead of 200. Additionally we run the risk of getting the error
``urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))``
In this PR, we address these two concerns, by 
1. Introducing a retry mechanism in case we get back non 200 status on a PUT call for uploading content.
2. Increasing the upload chunk size from 1 MB to 10 MB.
3. Introducing delay between successive …
> [VCDA-786] Additional fix for failures during template uploads to catalog. 

- ChangeLog
Updated version of pyvcloud to 20.0.1. Publishing the changelog via this PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/305)
> Update Changelog for pyvcloud v20.0.1

- pyvcloud/vcd/acl.py
- pyvcloud/vcd/api_extension.py
- pyvcloud/vcd/client.py
- pyvcloud/vcd/vapp.py
- pyvcloud/vcd/vdc.py
- pyvcloud/vcd/vm.py
- Fix Flake8 failures
- There are new failures in existing python files after Flake8 is updated to 3.6.0. There are two types of errors: "W504 line break after binary operator" & "F841 local variable 'e' is assigned to but never used". Fixing these failures. 
- @rajeshk2013 @rocknes @ckolovson
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/313)
> Fix Flake8 failures

- pyvcloud/vcd/platform.py
- system_tests/extnet_tests.py
Implementation of name and description update of an external network. Name and description both are optional, if none of them is provided, code returns without doing anything. It takes the name of the existing external network to find it. 
Testing done:
Added a test in extnet.tests and ran all the tests in this class. 
- @rocknes @rajeshk2013 @ckolovson
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/317)
> [VP-1153] Update name and description of an external network

- pyvcloud/vcd/gateway.py
- system_tests/gateway_tests.py
List external network ip allocations of the gateway.
The newly added function returns a dictionary that maps-
external network name to the list of ip addresses allocated to the gateway.
This CL has few formatting changes done by YPAF.
Testing Done: ran gateway_tests successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/324)
> VP-1239: List external network ip allocations.

- pyvcloud/vcd/client.py
- pyvcloud/vcd/utils.py
- pyvcloud/vcd/vdc.py
- system_tests/gateway_tests.py
[VP-1323]: Provide backward compatibility support for create gateway workflow
We have created two separate method for create gateway. One will work with API version greater than 30 and other one will 30 and lower.
I have tested manually against vCD 9.0 and 9.5 and found to be working fine.
@shashim22 @chaitanya118 @pandeys
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/330)
> VP-1323] Provide backward compatibility support for create gateway workflow

- pyvcloud/vcd/external_network.py
- system_tests/extnet_tests.py
VP-1243: Modify an IP range of a subnet in external network
This changelist involves the modification of a IP range in the subnet with the new IP range.
Testing done:
1. flake8 command succeeded
2. Test case passed, Ip Range modified in the subnet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/333)
> VP-1243: Modify an IP range of a subnet in external network

- pyvcloud/vcd/gateway.py
- system_tests/gateway_tests.py
VP-1292: List edge gateway's Configure IP Settings
This change set will list the edge gateway's Configure IP Settings 
Ex: {'External Networks':
['external_network_de99a4e2-f6d8-11e8-9e0c-9061ae543719'],
'Gateway': ['10.20.30.1/24'], 'Ip Address': ['10.20.30.2']}
Made changes to the following files:
gateway.py
gateway_tests.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/335)
> VP-1292:List edge gateway's Configure IP Settings

- pyvcloud/vcd/gateway.py
- system_tests/gateway_tests.py
VP-1293: Edit gateway Name
- Its replaces the old gateway name with the new name 
- User has to pass old gateway name and new gateway name as input to method edit_gateway_name
- Added edit_gateway_name(self, oldname=None, newname=None) to gateway.py
- Added test cases to gateway-tests.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/336)
> VP-1293: Edit gateway Name

- pyvcloud/vcd/external_network.py
- pyvcloud/vcd/platform.py
- system_tests/base_config.yaml
- system_tests/extnet_tests.py
- system_tests/helpers/portgroup_helper.py
Attach port groups of same type to an external network.
Testing done:
Verified portgroup attached from "vc2" is successful.
Verified portgroup attached from "vc3" is also successful.
System tests :passed
Verified for multiple vcd api versions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/339)
> VP-1257: Attach port groups to an external network

- pyvcloud/vcd/platform.py
- system_tests/vc_tests.py
List available portgroup names in a particular vCenter.
Note: 
This will be used by attach portgroup cli.
Testing done:
system test passed
Verified in the test environment that it prints correct values.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/343)
> VP-1450:List available portgroups in a vCenter

- pyvcloud/vcd/gateway.py
- system_tests/gateway_tests.py
VP-1298:Remove Sub allocate ip pool of gateway
Removes the sub allocate ip ranges of the gateway.
made changes to gateway.py and gateway_test.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/345)
> VP-1298:Remove Suballocate ip pool of gateway

- pyvcloud/vcd/external_network.py
- system_tests/extnet_tests.py
- system_tests/helpers/portgroup_helper.py
[PySdk] Detach port groups from an external network
This code has both functionality and test case for detaching port group
from external network.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/346)
> VP1259: [PySdk] Detach port groups from an external network

- pyvcloud/vcd/gateway.py
- pyvcloud/vcd/vdc.py
As part of CL https://github.com/vmware/pyvcloud/commit/71df56410034d9f122b77821d48d2d266dd28563, resource is None check was removed. It causes the failure for CLI command 'vcd vdc info'.
Removed the resource reload in case of None to keep the loading of resources on need basis as it was originally (before my changes).
Testing Done:
1: Successfully executed the pyvcloud->gateway_tests.py, pyvcloud->network_tests.py
2: Successfully executed the vcd-cli->vdc_network_tests.py and command vcd vdc info <name>
3: Tested Gateway creation successfully from CLI
@rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/347)
> Revert to lazy loading of resource during initialization of VDC objects.

- pyvcloud/vcd/external_network.py
- system_tests/extnet_tests.py
[PySDK] Delete an IP range of a subnet in external network
This changelist contains deletion of an IP range from a gateway of an
external network. This CLN also has test case related to this
functionality.
Testing done:
Test case for delete an ip range  is added to a test class
extnet_tests.py
All tests in extnet_tests passed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/349)
> VP 1447: [PySDK] Delete an IP range of a subnet in external network

- support/Jenkinsfile_sp_main
Provided options to run against existing vCD and respective API version
We can run the test against existing VCD environment and also provide other API version than default(32.0)
Testing Done: https://butler-vcd-staging.svc.eng.vmware.com/job/py-cloud-sdk/93/console
@guptaankit52 @chaitanya118
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/354)
> Provided options to run against existing vCD and respective API version

- pyvcloud/vcd/vdc_network.py
- system_tests/network_tests.py
User can change name, description and shared network state using this function
Testing Done: executed Network_test successfully
@chaitanya118 @guptaankit52
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/356)
> [VP-1357] Edit routed network's name, description and shared network state

- pyvcloud/vcd/external_network.py
- system_tests/extnet_tests.py
[PySDK] Delete an IP range of a subnet in external network
This changelist contains deletion of an IP range from a gateway of an
external network. This CLN also has test case related to this
functionality.
Testing done:
Test case for delete an ip range  is added to a test class
extnet_tests.py
All tests in extnet_tests passed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/358)
> VP-1147 : [PySDK] Delete an IP range of a subnet in external network

- pyvcloud/system_test_framework/environment.py
- system_tests/extnet_tests.py
Fix the external network tests failing with below error:
:58:34 Traceback (most recent call last):
08:58:34   File "/data/jenkins/jenkins-py-cloud-sdk-93/system_tests/extnet_tests.py", line 72, in test_0000_setup
08:58:34     TestExtNet._portgroupType)
08:58:34   File "/data/jenkins/jenkins-py-cloud-sdk-93/system_tests/helpers/portgroup_helper.py", line 58, in get_available_portgroup_name
08:58:34     'vCenter : ' + vim_server_name)
08:58:34 pyvcloud.vcd.exceptions.EntityNotFoundException: port group not found invCenter : vc1
Testing done:
1. "ExtNw" is created using dvportgroup.
2.  Extnet test passed and external network is using "VM NETWORK" portgroup.
--- …
> VP-1521: Fix external network tests

- pyvcloud/vcd/gateway.py
- system_tests/gateway_tests.py
[PySdk] List edge gateway's Syslog Server Settings
This CLN has code for listing tenant syslog server of a gateway. Test
case is also included. test case is skipped because set syslog server
code is not written before. unittest.skip will be removed once set
tenant syslog server is written.
Testing done:
Test case for list syslog server  is added to a test class
gateway_tests.py
All tests in gateway_tests passed.
---
This change is [<img …
> VP-1300: [PySdk] List edge gateway's Syslog Server Settings

- pyvcloud/system_test_framework/environment.py
- pyvcloud/vcd/client.py
- pyvcloud/vcd/metadata.py
- pyvcloud/vcd/utils.py
- pyvcloud/vcd/vapp.py
- pyvcloud/vcd/vdc.py
- requirements.txt
- system_tests/vapp_tests.py
- system_tests/vdc_tests.py
* Added a new class Metadata, that models metadata on first class objects in vCD.
* Updated vApp metadata operations to use the new Metadata class.
* Added support for vDC metadata get/set.
* Added system tests for vApp and vDC metadata
Also changed flufl.enum to python's standard enum module - flufl.enum doesn't support isinstance() method properly.
Testing done: Ran the updated vApp, vDC system tests, the runs were successful.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/348)
> [VCDA-840] Added metadata support for first class objects in vCD

- pyvcloud/vcd/external_network.py
- support/Jenkinsfile_pysdk.groovy
- system_tests/base_config.yaml
- system_tests/extnet_tests.py
- system_tests/run_system_tests.sh
Fix conatins following changes:
1: Check added for pvdc if not connected to any external network
2: Skip attach and detach portgroup if VC2 is not attached  …
Jenkins will run simple test bed for now and in abasence of second VC, in place of failing attach and detach VC, I am skipping.
They can be tested manually by providing any existing Multi-VC setup's json file.
Testing Done: https://butler-vcd-staging.svc.eng.vmware.com/job/py-cloud-sdk/109/console
@chaitanya118 @shashim22
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/370)
> Jenkins Test failure fix

- pyvcloud/vcd/external_network.py
[PySdk] List gateway IP sub-allocation
Cli command throws error as Error: local variable 'allocation_range'
referenced before assignment.
This CLN fixes the issue.
Testing done:
Test case for list associated ip sub allocation with gateway name  is
added to a test class extnet_tests.py
All tests in extnet_tests passed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/372)
> VP 1266: [PySdk] List gateway IP sub-allocation

- pyvcloud/system_test_framework/base_test.py
- pyvcloud/system_test_framework/environment.py
- pyvcloud/vcd/external_network.py
- system_tests/base_config.yaml
- system_tests/extnet_tests.py
This will list the associated direct org vDC networks to external network
Testing done: Test case passed
If the direct_ovdc_networks list has 0 items then below exception will be thrown.
pyvcloud.vcd.exceptions.EntityNotFoundException: No associated direct org vDC networks found
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/371)
> VP-1246: List associated direct org vDC networks in external network

- pyvcloud/vcd/vdc_network.py
- system_tests/extnet_tests.py
- system_tests/network_tests.py
[VP-1369,VP-1371,VP-1373]: add/update/delete metadata in vDC Routed Network
Support to add/update/delete metadat in a vDC Routed Network. Providing key and value adds an entry taking defualt values of domain (GENERAL), visibility (READWRITE) and metadata value type (MetadataStringValue). Specific valued of domain, visibility and metadata value type can also be provided. API for add and update is same, calling this updates if there is already an existing key with this name.
Also fixed Flake-8 formatting errors in extnet_tests.py and network_tests.py
Testing done:
Added test cases for add/update/delete metadata for vDC Routed Network in network_tests.py. All test of this class passes.
@rajeshk2013 @guptaankit52
---
This change is [<img src="https://reviewable.io/review_button.svg" …
> [VP-1369,VP-1371,VP-1373]: add/update/delete metadata in vDC Routed Network

- pyvcloud/vcd/gateway.py
After changing the Enum from flufl, I think validating the value whether it is part of GatewayBackingConfig is failing.
For now, I have removed the validation because it is okay. Just that it will fail in vCD.
Testing Done: Executed the gateway_test class and it succeeded without any error.
@chaitanya118
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/376)
> Fix test cases

- pyvcloud/vcd/gateway.py
- system_tests/gateway_tests.py
VP-1473,VP-1656,VP-1658: Configure default gateway,DNS and list
PYSDK support to add default gateway, enable/disable the dns realy and list the supported configured default gateway.
Implemented  configure_default_gateway, configure_dns_default_gateway, list_configure_default_gateway in gateway.py.
VP-1473: Configure default gateway
User would be able to enable the default gateway for provided external network and IP
VP-1656: Enable/Disable the DNS Relay
User would be able to enable/disable the DNS Relay
VP-1658:  List default gateway
User would be able list the configured default gateway
Testing:
Added test_0021_configure_gateway, test_0022_enable_dns_relay_gateway, test_0023_list_configure_default_gateway and test_0024_disable_configure_gateway to gateway_tests.py
All test cases are …
> VP-1473,VP-1656,VP-1658: Configure default gateway,DNS and list

- pyvcloud/vcd/client.py
- pyvcloud/vcd/vdc_network.py
- system_tests/network_tests.py
Adding support to list allocated IP Addresses of a org vdc routed network. Listing three columns, 'IP Address', 'Is Deployed' and 'Type'.
Testing done:
Added a test test_0090_list_routed_vdc_network_allocated_ip to network_test.py. All test cases in the class are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/382)
> [VP-1375] List IP allocations of a routed org vdc network

- pyvcloud/vcd/org.py
- Enhancement to org vdc to fetch admin org vdc resource
- Existing code gets non-admin org vdc. Adding admin option helps in getting more information
like what is backing Ovdc etc. Tested manually with python script
@rocknes @sahithi @sompa @rajeshk2013 @andrew-ni @harshneelmore
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/384)
> Add option for getting admin view of org vdc

- pyvcloud/system_test_framework/base_test.py
- pyvcloud/system_test_framework/environment.py
- pyvcloud/vcd/gateway.py
- pyvcloud/vcd/nat_rule.py
- pyvcloud/vcd/network_url_constants.py
- system_tests/base_config.yaml
- system_tests/nat_rule_tests.py
Add a SNAT or DNAT rule to an edge gateway.
Delete a SNAT or DNAT rule to an edge gateway.
This will support tcp/udp/icmp protocols for NAT rule.
Testing done:
Test cases passed
Setup
Add NAT rule
Delete NAT rule
Teardown
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/385)
> VP-1584,VP-1588: Add and delete nat rule

- pyvcloud/vcd/gateway.py
- pyvcloud/vcd/nat_rule.py
- system_tests/nat_rule_tests.py
Get all details of a Nat Rule.
List all the Nat Rules associated with gateway
e.g.
{'ID': 196609, 'OriginalAddress': '2.2.3.7', 'OriginalPort':
'any', 'TranslatedAddress': '2.2.3.8', 'TranslatedPort':
'any', 'Action': 'snat', 'Protocol': 'any', 'Enabled': True,
'Logging': False, 'Description': ''}
Testing done:
Added below tests:
test_0015_get_nat_rule_info
test_0020_list_nat_rules
test cases status: passed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/387)
> VP-1590,1594: Get Nat Rule info and list Nat Rules

- pyvcloud/vcd/vdc.py
- system_tests/network_tests.py
Adds `network_cidr` param to `create_isolated_vdc_network()` method in vdc.py
This PR bring `create_isolated_vdc_network()` inline with `create_routed_vdc_network()`. They both now use `network_cidr` param rather then `gateway_ip` and `netmask`.  `network_tests.py` had been updated to reflect the changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/373)
> Add cidr to isolated vdc network

- pyvcloud/vcd/client.py
- pyvcloud/vcd/vdc_network.py
- system_tests/network_tests.py
Added functionality to list of vApps connected to an org vdc routed network.
Testing done:
Added a test case test_0100_list_connected_vapps to network_tests.py. All test cases in this class are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/390)
> [VP-1377]: List connected vApps to a org vdc routed network

- pyvcloud/vcd/gateway.py
- pyvcloud/vcd/network_url_constants.py
- system_tests/static_route_tests.py
Below functionalities related to Static route is covered:
1) Add Static Routes Between vApp/Org Vdc Networks to different networks or external network.
2) This will list static routes in below format.
[{'Network': '192.169.1.0/24', 'Next Hop': '2.2.3.80', 'MTU': 1500}]
Testing done:
test_0000_setup (Test to create a static route)
status: passed
test_0001_list_static_routes
status: passed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/396)
> VP-1604,1611: Add and List Static Routes

- pyvcloud/vcd/vdc_network.py
- system_tests/network_tests.py
It is failing because media type of vDC link in routed network is different in case of org admin and system admin. Added a check look for admin vDC link in case system admin is logged in. Otherwise, look for vDC link.
Testing done:
Added two test cases test_0100_list_connected_vapps_org_admin, test_0110_list_connected_vapps_sys_admin in network_tests.py. All tests in this class are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/398)
> [VP-1748]: Listing of connected vApps fails for system admin

- pyvcloud/vcd/vdc_network.py
- system_tests/network_tests.py
Added a feature to delete static IP pool from a routed network. It also removes if there is just one IP pool.
Testing done:
Added test_0078_remove_static_ip_pool to network_tests.py. All tests cases in this class are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/399)
> [VP-1365]: Remove static IP pool in routed network under Network Specification

- pyvcloud/vcd/api_extension.py
- system_tests/api_extension_tests.py
CSE would be using this function, as opposed to unregistering and re-registering with updated properties. The function docstring has relevant information.
This function takes a service name, namespace, routing key, and exchange name.
We update the currently registered extension to have the specified routing key and exchange name.
We return the service href, following the precedence from enable_extension()
@rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/379)
> Add update_extension function to api_extension.py

- pyvcloud/vcd/client.py
- pyvcloud/vcd/vdc_network.py
- system_tests/network_tests.py
User can convert to sub-interface and revert back to original state.
Testing Done: Added new test case to convert to sub-interface and then revert back using system user and org admin.
Executed the routed network test class successfully
@shashim22 @guptaankit52
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/400)
> Convert to subinterface

- system_tests/api_extension_tests.py
The api_extension system test was failing because of a wrong key. 
Also fixed client being leaked from another test in the same module.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/402)
> Fixed failing api-extension system tests.

- pyvcloud/vcd/client.py
- pyvcloud/vcd/gateway.py
- pyvcloud/vcd/vdc_network.py
- system_tests/network_tests.py
In order to be able to convert to Distributed routing, Gateway need to have Distributed routing enabled. Existing code doesn't serve the complete purpose. It includes this changes as well.
Testing Done: Added new test and executed the routed network test successfully.
@guptaankit52 @shashim22
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/401)
> [VP-1387] Convert to Distributed Routing

- system_tests/extnet_tests.py
Update of external network gets stuck in vCD. We have observed this behavior in multiple run. Commenting for now.
Reference: https://sp-taas-vcd-butler.svc.eng.vmware.com/view/all/job/Preflight-pysdk-1.0-STF/43/consoleFull
@shashim22
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/408)
> Comment update of external network test case as it gets stuck in vCD

- pyvcloud/system_test_framework/environment.py
- system_tests/extnet_tests.py
$ vcd version
Traceback (most recent call last):
File "/home/travis/virtualenv/python3.6.3/bin/vcd", line 6, in
<module>
from vcd_cli.vcd import vcd
File
"/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/vcd_cli/vcd.py",
line 115, in <module>
from vcd_cli import ipsec_vpn  # NOQA
File
"/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/vcd_cli/ipsec_vpn.py",
line 16, in <module>
from pyvcloud.system_test_framework.environment import Environment
File
"/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pyvcloud/system_test_framework/environment.py",
line 22, in <module>
from helpers.portgroup_helper import PortgroupHelper
ModuleNotFoundError: No module named 'helpers'
The command "vcd version" exited with 1.
This issue is fixed by providing correct …
> Fix for percheck failure.

- pyvcloud/vcd/firewall_rule.py
- system_tests/firewall_rule_tests.py
VP-1538 : [PySDK] Edit Firewall rule name
Enhanced the update feature to support edit of firewall rule name as well .
Testing Done:
Enhanced test_0050_edit to firewall_rule_tests.py to verify name edit. All test cases in this class are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/425)
> VP-1538 : [PySDK] Edit Firewall rule name

- pyvcloud/system_test_framework/environment.py
CLI test case is failing for the same reason
18:57:01 ======================================================================
18:57:01 ERROR: login_and_vcd_tests (unittest.loader._FailedTest)
18:57:01 ----------------------------------------------------------------------
18:57:01 ImportError: Failed to import test module: login_and_vcd_tests
18:57:01 Traceback (most recent call last):
18:57:01   File "/usr/local/lib/python3.7/unittest/loader.py", line 154, in loadTestsFromName
18:57:01     module = __import__(module_name)
18:57:01   File "/data/jenkins/jenkins-Preflight-vcdcli-1.0-STF-27/system_tests/login_and_vcd_tests.py", line 21, in <module>
18:57:01     from pyvcloud.system_test_framework.base_test import BaseTestCase
18:57:01   File …
> Failing System Test complaining No module named 'system_test'

- pyvcloud/vcd/external_network.py
- system_tests/extnet_tests.py
Fix the following in external network:
1. list-direct-org-vdc-network
2. list-vsphere-network
Added filter for external network
Testing done: 
Below commands returning correct result
vcd network external list-direct-org-vdc-network extnw1
vcd network external list-direct-org-vdc-network extnw1 --filter connectedTo==*
vcd network external list-vsphere-network ExtNw
vcd network external list-vsphere-network ExtNw --filter networkName==*
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/426)
> [Fix]: listing of vsphere network and direct org vdc network

- pyvcloud/vcd/firewall_rule.py
- system_tests/firewall_rule_tests.py
VP-1827 : [PySDK] Run firewall rule test cases as org admin.
Enhance the feature to run as org admin firewall_rule_tests.py is modified.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/429)
> VP-1827 : [PySDK] Run firewall rule test cases as org admin

- system_tests/base_config.yaml
Jenkins run not able to take the API provided using jenkins because it can only replace 30.0 as written in run_system_tests.sh file.
@guptaankit52 @shashim22
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/431)
> Jenkins run not able to take the API provided

- pyvcloud/vcd/external_network.py
New subnet is added as disabled, making it enabled to match vCloud UI behavior.
Testing done:
Ran extnet_tests.py, all test cases are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/433)
> Enable new subnet by default

- pyvcloud/vcd/external_network.py
list_associated_direct_org_vdc_networks() and list_vsphere_network() in external_network are throwing exception if the result is an empty list.
Testing done:
Ran extnet_tests.py, all test cases are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/434)
> List commands in external_network throws exception on empty result

- system_tests/extnet_tests.py
- system_tests/vdc_tests.py
Extnet_tests were failing with ModuleNotFound Error.
https://sp-taas-vcd-butler.svc.eng.vmware.com/job/Preflight-pysdk-1.0-STF/55/console
Removed the system_tests suffix.
It also included the fix for getVdc for not available vdc
Testing Done: Executed the external tests successfully.
@guptaankit52 @kousgy123
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/436)
> Jenkin'e test failure

- pyvcloud/vcd/firewall_rule.py
- system_tests/firewall_rule_tests.py
VP-1544 : [PySDK] Change the sequence of the firewall rules.
Providing support to change firewall rule's sequence of rule id.
Testing Done:
Added test_0091_update_firewall_rule_sequance to firewall_rule_tests.py. All test cases in this class are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/439)
> VP-1544 : [PySDK] Change the sequence of the firewall rules

- pyvcloud/vcd/firewall_rule.py
- system_tests/firewall_rule_tests.py
VP-1791 : [PySDK] delete values from Firewall Source.
Providing support to delete firewall rule's source value of rule id.
Testing Done:
Added test_0071_delete_firewall_rule_source to firewall_rule_tests.py. All test cases in this class are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/441)
> VP-1791 : [PySDK] delete values from Firewall Source

- pyvcloud/vcd/vapp.py
- system_tests/vapp_tests.py
This CL adds function to VApp class, to edit name and description.
Added vapp_tests.test_0011_edit_vapp_name_desc test for the same.
Testing done: ran the newly added test cases locally.
tested vcd-cli commands for the same.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/442)
> VP-1401: edit name and description of a vapp

- pyvcloud/vcd/org.py
- system_tests/vcd_user.py
- Added functionality to update_user function to change the role of an existing organization user with a supplied role.
- Above change is required by CSE to update an existing users role with CSE right included role.
- Added system tests for create_user(), list_user(), enable_user(), update_user_role() and delete_user().
- Tested the above changes manually and by using pyvcloud system tests.
- @rocknes, @sahithi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/432)
> [VCDA-863] Reassign role of an existing user in vCD

- pyvcloud/vcd/firewall_rule.py
- system_tests/firewall_rule_tests.py
VP-1840 : [PySDK] List Firewall Destination.
Providing support to list firewall rule's destination of rule id.
Testing Done:
Added test_0082_list_firewall_rule_destination to firewall_rule_tests.py. All test cases in this class are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/445)
> VP-1840 : [PySDK] List Firewall Destination

- pyvcloud/vcd/firewall_rule.py
- system_tests/firewall_rule_tests.py
VP-1793 : [PySDK] delete values from Firewall Destination.
Providing support to delete firewall rule's destination value of rule id.
Testing Done:
Added test_0096_delete_firewall_rule_destination to firewall_rule_tests.py. All test cases in this class are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/447)
> VP-1793 : [PySDK] delete values from Firewall Destination

- pyvcloud/vcd/gateway.py
Fixed below errors when running the vcd-cli command to reorder nat rule.
Error: local variable 'insert_nat_rule' referenced before assignment
Error: Argument 'element' has incorrect type (expected lxml.etree._Element, got NoneType)
Test done:
All Nat rule tests passed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/448)
> Modify pysdk as per vcd-cli for reorder NAT rule

- pyvcloud/vcd/firewall_rule.py
- system_tests/firewall_rule_tests.py
VP-1845 : [PySDK] List Firewall Service.
Providing support to list firewall rule's services of rule id.
Testing Done:
Added test_0083_list_firewall_rule_service to firewall_rule_tests.py. All test cases in this class are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/450)
> VP-1845 : [PySDK] List Firewall Service

- pyvcloud/vcd/firewall_rule.py
- system_tests/firewall_rule_tests.py
VP-1795 : [PySDK] delete values from Firewall Service.
Providing support to delete firewall rule's service of rule id.
Testing Done:
Added test_0097_delete_firewall_rule_service to firewall_rule_tests.py. All test cases in this class are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/451)
> VP-1795 : [PySDK] delete values from Firewall Service

- pyvcloud/vcd/gateway.py
- pyvcloud/vcd/ipsec_vpn.py
- system_tests/ipsec_vpn_test.py
This CLN contains bugs reported for ipsec vpn. This fix is in pysdk.
These methods does not require id because they are at global level.
Methods moved to gateway class.Test cases also modified.
vcd gateway services ipsec_vpn
enable-activation-status -h
Usage: vcd gateway services ipsec_vpn enable-activation-status
[OPTIONS] <gateway name> <IPsec VPN id>
Options:
--enable / --disable enable/disable IPsec VPN
-h, --help Show this message and exit.
2=> IPsec VPN id should not be required.remove this.
vcd gateway services ipsec_vpn
enable-logging -h
Usage: vcd gateway services ipsec_vpn enable-logging [OPTIONS] <gateway
name>
<IPsec VPN id>
Options:
--enable / --disable enable/disable global logging of IPsec VPN
-h, --help Show this message and exit.
3=> IPsec VPN id should not be …
> VP-1228: [PYSDK] TestFest bugs IPSEC Vpn

- pyvcloud/system_test_framework/utils.py
- pyvcloud/vcd/client.py
- pyvcloud/vcd/vapp.py
- system_tests/vapp_tests.py
This CL adds reset_vapp_network and delete_vapp_network functions to vapp.
Added the following test cases to vapp: test_0120_reset_vapp_network, test_0130_delete_vapp_network
Testing done: ran all the vapp tests locally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/449)
> VP-1394, VP-1397: add reset and delete vapp network functions.

- pyvcloud/vcd/vapp.py
- system_tests/vapp_tests.py
VP-1923 : [PySDK] Add IP range to vApp network.
Providing support to add IP range in vapp network.
Testing Done:
Added test_0122_add_ip_range to vapp_tests.py. All test cases in this class are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/464)
> VP-1923 : [PySDK] Add IP range to vApp network

- pyvcloud/vcd/vapp.py
- system_tests/vapp_tests.py
VP-1925 : [PySDK] Update IP range of vApp network.
Providing support to update IP range in vapp network.
Testing Done:
Added test_0123_add_ip_range to vapp_tests.py. All test cases in this class are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/466)
> VP-1925 : [PySDK] Update IP range of vApp network

- pyvcloud/system_test_framework/depends.py
- pyvcloud/vcd/vapp.py
- system_tests/vapp_tests.py
VP-1927 : [PySDK] Delete IP range from vApp network.
roviding support to delete IP range in vapp network.
Testing Done:
Added test_0125_add_ip_range to vapp_tests.py. All test cases in this class are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/468)
> VP-1927 : [PySDK] Delete IP range from vApp network

- pyvcloud/vcd/vapp.py
- system_tests/vapp_tests.py
VP-1929 : [PySDK] Add DNS details to vApp network.
Providing support to add and update DNS details in vapp network.
Testing Done:
Added test_0125_add_update_dns_vapp_network to vapp_tests.py. All test cases in this class are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/470)
> VP-1929 : [PySDK] Add DNS details to vApp network

- pyvcloud/vcd/vdc.py
When creating EdgeGateway for VDC it is possible to provide IP settings with a ip address. However SDK fail to configure the specified ip in tern edge gateway gets the next available ip in the subnet. Issue is related to comparison of netmask str and int. Solution is to cast the value to int and compare.
Fixes 481
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/482)
> Fix issue configuring IP settings in EdgeGateway

- pyvcloud/vcd/vdc.py
Comparison of int and str variable prevents configuring Sub-Allocate IP Pool. String parameter cast to int to make the comparison work
Method signature documentation updates
Signed-off-by: Chaminda Divitotawela <cdivitotawela@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/483)
> Fix VDC EdgeGateway Sub-Allocate IP Pool configuration

- system_tests/gateway_tests.py
Test case is failing with error The following IP addresses are already
------------------
12:19:26 pyvcloud.vcd.exceptions.BadRequestException: Status code: 400/BAD_REQUEST, [ 0d35f753-becc-4183-b3a7-579528f2bbc7 ] The following IP addresses are already
being used: 2.2.3.2. (request id: 0d35f753-becc-4183-b3a7-579528f2bbc7)
-----------------
https://sp-taas-vcd-butler.svc.eng.vmware.com/job/Preflight-pysdk-1.0-STF/104/consoleFull
Testing Done: Executed the gateway_tests successfully
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/484)
> Jenkin's test failure with error "The following IP addresses are already"

- system_tests/base_config.yaml
- system_tests/gateway_tests.py
Gateway setup is failing complaining "The following IP addresses are already being used:2.2.3.2"
We were sending same(2.2.3.2) IPs in IP Range field.
https://sp-taas-vcd-butler.svc.eng.vmware.com/job/Preflight-pysdk-1.0-STF/105/testReport/junit/gateway_tests/TestGateway/test_0000_setup/
Testing Done: Executed gateway_test successfully
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/485)
> Fix for jenkin test failure

- pyvcloud/vcd/vdc.py
Previously self.client.delete_resource(href, force) call passing the force value but the delete_resource was taking default value.
In this changes self.client.delete_resource(href, force=force) taking the passed value.
Status code: 400/BAD_REQUEST, [ cadad549-cfb7-4151-9021-e19369a9efbe ] 
The requested operation could not be executed on vApp 
"customized_vApp_ea88a014-453e-11e9-b636-0242ac110002". Stop the vApp 
and try again. (request id: cadad549-cfb7-4151-9021-e19369a9efbe)
- (Optional) …
> vapp_tests.TestVApp.test_9998_teardown Failure Fix

- pyvcloud/vcd/vapp_firewall.py
- system_tests/vapp_firewall_tests.py
VP-1943 : [PySDK] Enable Firewall of vApp network.
VP-1945 : [PySDK] Disable Firewall of vApp network.
Providing support to Enable/Disable firewall service of vapp network.
Testing Done:
Added test_0012_enable_firewall_service to vapp_firewall_tests.py. All test cases in this class are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/490)
> VP-1943, VP-1945

- system_tests/vm_tests.py
[PYVCLOUD] unittest.skip : getVC fix
This CLN removes unitTest.skip for getVc() method in vm_tests.py file.
Implementation is corrected to solve the issue.
Testing Done:
All test cases in vm_tests.py are executing successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/503)
> VP-2194: [PYVCLOUD] unittest.skip : getVC fix

- pyvcloud/vcd/client.py
- pyvcloud/vcd/vapp.py
- system_tests/vapp_tests.py
VP-2086:[PySDK]Discard suspended state.
VP-2090:[PySDK] Enter maintenance mode.
VP-2092:[PySDK] Exit maintenance mode.
VP-2198:[PySDK]suspend vapp
This CLN contains above functionalities and corresponding test cases.
Testing Done:
All test cases in vapp_tests class are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/504)
> VP-2086,VP-2090,VP-2092,VP-2198

- pyvcloud/vcd/vapp.py
- system_tests/vapp_tests.py
VP-2094 : [PySDK] Upgrade Virtual Hardware version vapp.
Adding a support to upgrade virtual hardware of all vm belongs to vapp.
Testing Done:
Added def_0100_upgrade_virtual_hardware to vapp_tests.py. All test cases in this class are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/510)
> VP-2094 : [PySDK] Upgrade Virtual Hardware version vapp

- pyvcloud/vcd/vm.py
- system_tests/vm_tests.py
VP-2035: [PYSDK]Copy to VM from one vApp to another
This CLN contains copying VM from one vApp to another vApp. copy_to()
method is exposed in vm.py class and corresponding test case added. This
method will take source vapp, target vapp and VM name as argument.
Testing Done:
test method test_0072_copy_to() is added in test class vm_tests.py. It
is executing successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/514)
> VP-2035: [PYSDK]Copy to VM from one vApp to another

- pyvcloud/vcd/vdc.py
- system_tests/vapp_tests.py
Added method(list_vapp_details) to get vApp Details with filter
" vcd vapp list" command currently not having filter to get vapp list based on some option provided by user. With this change we have added list_vapp_details() methods to get vApp details based on provided filter, it will accept below filters :
vcd vapp list --filter ownerName==ownername
vcd vapp list --filter numberOfVMs==number
vcd vapp list --filter name==vapp-name
vcd vapp list --filter vdcName==ovdc-name
Also we have added the testcase for the same
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/516)
> Added method list_vapp_details() and test-case for list_vapp_details()

- pyvcloud/vcd/vm.py
- system_tests/vm_tests.py
VP-2039: [PySDK] Delete VM
This CLN contains functionality to delete a VM and corresponding test
case test_0074_delete_vm is added in vm_tests.py file.
Testing Done:
Method test_0074_delete_vm is added in vm_tests.py file and it is
executing successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/521)
> VP-2039: [PySDK] Delete VM

- examples/tenant-onboard.py
- examples/tenant-remove.py
VP-2393: PYPI api version fix
This CLN contains change for refreshing PYPI build. It makes client to
choose API_VERSION from the file not the heighest supported version.
Testing Done:
tenant-onboard.py file is tested and it is executing successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/524)
> VP-2393: PYPI api version fix

- system_tests/idisk_tests.py
VP-2394: [PYSDK]idisk test case fix
This CLN fix test cases of independent disk which are failing because of
size of them. New VCD accepts at-lease size of 1 mb. Changes has done
accordingly.
Testing Done:
idisk_tests.py is executing successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/525)
> VP-2394: [PYSDK]idisk test case fix

- pyvcloud/vcd/client.py
- pyvcloud/vcd/vapp.py
- system_tests/vapp_tests.py
VP-2100 : [PySDK] Copy to vapp.
This CLN contains copying Vapp from one vdc  to another vdc or same vdc. 
copy_to() method is exposed in vapp.py class and corresponding test case added. 
This method will take source vapp, target vapp anme and vdc as argument.
Testing Done:
test method test_0150_copy_to() is added in test class vapp_tests.py. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/517)
> VP-2100 : [PySDK] Copy to vapp

- system_tests/run_system_tests.sh
VP-2409: [PYSDK] Feature to add test files automatically.
This feature will enable developer not to add their new test files into
run_system_tests.sh manually. New test files will be picked
automatically. There is a provision for unstable tests which can be
enabled for particular test files manually.
Testing Done:
CI/CD will test the script in next run.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/530)
> VP-2409: [PYSDK] Feature to add test files automatically.

- pyvcloud/vcd/vapp.py
- system_tests/vapp_tests.py
VP-2102 : [PySDK] Move to vapp.
This CLN contains moving a Vapp from one vdc to another vdc.  
move_to() method is exposed in vapp.py class and corresponding test case added.  
This method will take target vdc as argument.
test method test_0160_move_to() is added in test class vapp_tests.py.  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/531)
> VP-2102 : [PySDK] Move to vapp

- pyvcloud/vcd/vapp.py
- system_tests/vapp_tests.py
VP-2106 : [PySDK] create snapshot of vapp.  
This CLN contains creating a snapshot of a vapp.  
create_snapshot() method is exposed in vapp.py class and corresponding test case added.  
test method test_0170_create_snapshot() is added in test class vapp_tests.py.  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/533)
> VP-2106 : [PySDK] create snapshot of vapp

- pyvcloud/vcd/vapp.py
- system_tests/vapp_tests.py
VP-2108 : [PySDK] Revert to snapshot vapp
VP-2110 : [PySDK] Remove the snapshot vapp
This CLN contains revert to snapshot and remove all snapshot of a vapp.
snapshot_revert_to_current() and snapshot_remove() methods is exposed in vapp.py class and corresponding test case added.
test methods test_0180_snapshot_revert_to_current() and test_0190_snapshot_remove() is added in test class vapp_tests.py.  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/534)
> VP-2108 and VP-2110

- system_tests/vm_tests.py
VP-2047: [pySdk] Attach Disk
This CLN contains attach disk test case in pyvcloud which tests already
existing functionality.
Testing Done:
test_0110_attach_independent_disk is added in vm_tests.py file and it is
executing successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/535)
> VP-2047: [pySdk] Attach Disk

- examples/tenant-onboard.py
- pyvcloud/vcd/org.py
- pyvcloud/vcd/utils.py
- pyvcloud/vcd/vdc.py
vCD code has gone under changes for API version 33 for entities Org and VDC. They started passing the admin vDC link for Org GET if requested by System Admin User.
Fix will check if resource is of type admin then fetch its alternate non-admin resource for performing vapp instantiate operation.
Manually executed the tenant-onboard.py and found to be working fine.
Error stack trace for reference-----
08:45:19 Traceback (most recent call last):
08:45:19   File "/data/jenkins/jenkins-Preflight-pysdk-1.0-STF-245/examples/tenant-onboard.py", line 272, in <module>
08:45:19     vapp_resource = vdc.instantiate_vapp(**vapp_cfg)
08:45:19   File "/data/jenkins/jenkins-Preflight-pysdk-1.0-STF-245/jenkins-venv/lib/python3.7/site-packages/pyvcloud/vcd/vdc.py", line 223, in instantiate_vapp
08:45:19 …
> C to t failure

- pyvcloud/system_test_framework/environment.py
- pyvcloud/vcd/org.py
For API version lesser than 33, evaluating the link was not getting called. Result in CToT failure.
After the fix, Tested locally against API version 33 and 32 and found to be working fine.
@kkkothari
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/545)
> Fix get_catalog for API version less than 33

- pyvcloud/vcd/system.py
- Bug effectively renders function useless as only empty orgs
can be deleted
- Fixes Issue #508
- Issue provides a detailed analysis of the issue and resolution.
@pandeys With this PR, we should be able to quickly close out this issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/523)
> Fixed bug with delete_org function

- pyvcloud/vcd/client.py
Before the fix, log get rolled over after the default size and never get captured.
After this fix, log will rollover to new file once the default size of log file (30 mb) will get filled.
Testing Done: Locally I am able to see it creating new files, once the current log file cross the size limit.
@pandeys @kkkothari
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/548)
> Adding support for log roll over

- pyvcloud/vcd/client.py
CToT is failing while executing list-vdc-resource.py
Error stack trace-------
16:40:36 Logging in: host=wdc-vcd-sp-static-34-63.eng.vmware.com, org=Test1, user=user1
16:40:36 Traceback (most recent call last):
16:40:36   File "/data/jenkins/jenkins-Preflight-pysdk-1.0-STF-261/examples/list-vdc-resources.py", line 39, in <module>
16:40:36     client = Client(host, verify_ssl_certs=False)
16:40:36   File "/data/jenkins/jenkins-Preflight-pysdk-1.0-STF-261/jenkins-venv/lib/python3.7/site-packages/pyvcloud/vcd/client.py", line 718, in __init__
16:40:36     self._get_defaut_logger(file_name=log_file)
16:40:36   File "/data/jenkins/jenkins-Preflight-pysdk-1.0-STF-261/jenkins-venv/lib/python3.7/site-packages/pyvcloud/vcd/client.py", line 773, in _get_defaut_logger
16:40:36     filename=file_name, …
> Fix CToT failure in case of file_name is not provided.

- pyvcloud/vcd/vapp.py
- system_tests/vapp_tests.py
VP-2593 :[PySDK] Show DNS detail of Vapp Network.
This CLN contains show DNS details of Vapp Network functionality.
dns_detail_of_vapp_network() methods is exposed in vapp.py class and corresponding test case added.
Testing Done:
test methods test_0127_dns_detail_of_vapp_network() is added in test class vapp_tests.py.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/550)
> VP-2593 :[PySDK] Show DNS detail of Vapp Network

- system_tests/vm_tests.py
[PySDK] Detach Disk
This CLN contains test case for detach independent disk from VM.
Functionality is already included in Vapp.py file.
Testing Done:
Test case test_0120_detach_independent_disk is added in vm_tests.py file
and it is executing successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/536)
> VP-2049: [PySDK] Detach Disk

- test-requirements.txt
Docstyle issue with flake8.
This issue is due to pydocstyle version 4.0.
"flake8-docstrings" failed during execution due to "module 'pydocstyle' has no attribute 'tokenize_open'"
RROR: InvocationError for command /data/jenkins/jenkins-Preflight-pysdk-1.0-STF-272/.tox/flake8/bin/flake8 pyvcloud/vcd (exited with code 1)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/552)
> Docstyle issue with flake8

- pyvcloud/vcd/client.py
- pyvcloud/vcd/vm.py
- system_tests/vm_tests.py
[PySDK] Reload from VC
This CLN contains VM functionality to reload from VC. Test cases are
also attached in file vm_tests.py file.
Testing Done: Test method test_0150_reload_from_vc is added in
vm_tests.py file and it is executing successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/553)
> VP-2072: [PySDK] Reload from VC

- pyvcloud/vcd/client.py
- pyvcloud/vcd/vapp.py
- system_tests/vapp_tests.py
VP-1399 : [PySdk] Synchronize syslog server settings
VP-2598 : [PySdk] Make connection of vapp network
This CLN contains Make connection of vapp network with org vdc network of Vapp and
Synchronize syslog server settings.
sync_syslog_settings() and connect_vapp_network_to_ovdc_network() methods is exposed in vapp.py class and corresponding test case added.
Testing Done:
test methods test_0130_connect_vapp_network_to_ovdc_network()  and test_0131_sync_syslog_settings are added in test class vapp_tests.py.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/555)
> VP-1399, VP-2598

- pyvcloud/vcd/client.py
- pyvcloud/vcd/vm.py
- system_tests/vm_tests.py
[PySDK] CUstomize at Next Power ON
This CLN contains VM functionality to customize at next power on. Test
case is not included because corresponding API returns 204 no content.
Testing Done:
Manual testing done. In VCD host, guest customization logs tested
manually while powering on the VM.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/556)
> VP-2079: [PySDK] CUstomize at Next Power ON

- pyvcloud/vcd/org.py
- system_tests/catalog_tests.py
- Functionality to support add, delete, retrieve metadata on catalog item
- New methods are added to support metadata operations on catalog item that belong to an organization.
Testing done:
Tested with standalone script as well as thru postman rest client
TODO: Sytem tests
@rocknes @rajeshk2013 @andrew-ni @harshneelmore
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/557)
> VCDA 1080:[pyvcloud] support for add retrieve delete catalog item metadata

- pyvcloud/vcd/client.py
- pyvcloud/vcd/vm.py
- system_tests/vm_tests.py
VP-2065: [PySDK]Update selected VM general properties.
This CLN contains Update general setting of VM.
update_general_setting()  methods is exposed in vm.py class and corresponding test case added.
Testing Done:
test methods test_0180_update_general_setting() is added in test class vm.py.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/558)
> VP-2065: [PySDK]Update selected VM general properties

- pyvcloud/vcd/client.py
- pyvcloud/vcd/vdc.py
- pyvcloud/vcd/vm.py
- system_tests/base_config.yaml
- system_tests/vm_tests.py
VP-2021: [PySDK]Power on with force Recustomization for a VM
VP-2676: [PYSDK] Get GuestCustomizationSectionStatus
VP-2689: [PYSDK] Enable GC
This CLN contains above three functionalities. One new OVA file with OS
is added for guest customization related test cases. VP-2021 has
dependency on VP-2676 and VP-2689. All three stories test cases are
added.
Testing Done:
Three test cases are added for above stories in vm_tests.py. Validation
for customize at next power on and power on and force customization is
still not correct by API behavior.It will be changed in next gc related
check-ins.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/559)
> VP-2021,VP-2676,VP-2689 :Power on with force Recustomization for a VM

- pyvcloud/vcd/client.py
- pyvcloud/vcd/vdc.py
- Support added to handle list, add, remove vdc compute policy from org vDC
- Add and remove methods accept "href" as param. This "href" is an unique identifier of a policy generated by /cloudapi/computePolicies. 
- Tested and verified with scripts that uses these new API and Postman rest client.
- NOTE: Since these methods need a valid unique "href" generated by /cloudapi/ end point and it is not supported by pyvcloud, system tests are skipped for this PR.
@rocknes @rajeshk2013 @andrew-ni @harshneelmore
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/560)
> VCDA-1081:[pyvcloud] Add support to list/add/remove vdc compute policy from org VDC

- pyvcloud/vcd/vapp.py
- system_tests/vapp_tests.py
VP-1908 : [PySDK] Create vApp network using orgVdc network
VP-1921: [PySDK] Enable vApp Fence
VP-2633: [PySDK] Enable disble download in vapp	
This CLN contains Create vApp network using orgVdc network, Enable vApp Fence and  Enable disble download in vapp.
disable_download(),  create_vapp_network_from_ovdc_network() and enable_fence_mode() methods are exposed in vapp.py class and corresponding test case added.
Testing Done:
test methods test_0200_create_vapp_network_from_ovdc_network() and test_0201_enable_fence_mode are added in test class vapp.py.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/561)
> VP-1908, VP-1921, VP-2633

- pyvcloud/vcd/vapp.py
- system_tests/vapp_tests.py
VP-2638: [PySDK]show Lease setting in vapp.
This CLN contains get lease setting details in vapp.
get_lease() methods is exposed in vapp.py class and corresponding test case added.
Testing Done:
test methods test_0081_get_lease()  is added in test class vapp_tests.py.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/562)
> VP-2638: [PySDK]show Lease setting in vapp

- pyvcloud/vcd/client.py
- pyvcloud/vcd/vapp.py
- system_tests/vapp_tests.py
VP-2642 [PySDK]Start time action in vapp
VP-2643 [PySDK]Stop time action in vapp
This CLN contains update startup section in vapp.
update_startup_section() methods is exposed in vapp.py class and corresponding test case added.
Testing Done:
test methods test_0210_update_startup_section() is added in test class vapp_tests.py.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/566)
> VP-2642, VP-2643

- pyvcloud/vcd/client.py
- pyvcloud/vcd/vapp.py
- system_tests/vapp_tests.py
VP-2637:[PySDK]show product section in vapp
VP-2720:[PySDK]show startup section of vapp 
VP-2725:[PySDK]update product section in vapp
This CLN contains show product section, show startup section and update product section of Vapp.
get_startup_section(), get_product_sections() and update_product_section methods are exposed in vapp.py class and corresponding test case added.
Testing Done:
test methods test_0220_get_startup_section(), test_0230_update_product_section() and test_0240_get_product_sections() are added in test class vapp_tests.py.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/568)
> VP-2637, VP-2720, VP-2725

- pyvcloud/vcd/client.py
- pyvcloud/vcd/vm.py
- system_tests/vm_tests.py
VP-2624: [PYSDK] get compliance result
This CLN contains functionality to get compliance result. It calls VCD
GET API for complianceResult.
Testing Done:
test method test_0230_get_compliance_result is added in vm_tests.py
file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/569)
> VP-2624: [PYSDK] get compliance result

- pyvcloud/vcd/client.py
- pyvcloud/vcd/vm.py
- system_tests/vm_tests.py
VP-2634: [PYSDK] Get current metrics
VP-2728: [PYSDK] List subset of current metrics
VP-2730: [PYSDK] List historic metrics
This CLN contains listing of current and historic metrics of VM.
Testing Done:
Test method test_0240_list_all_current_metrics and
test_0250_list_subset_current_metrics added for current metrics. For
historic metrics, we need VM monitoring set-up which is not part of test
lab setup.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/570)
> VP-2634,VP-2728,VP-2730: List VM Metrics

- pyvcloud/vcd/org.py
- pyvcloud/vcd/utils.py
- pyvcloud/vcd/vdc.py
-  Support added to add or remove a given compute policy to all vms of given vapp-template in a catalog.
-  Add and remove methods accept "href" as param. This "href" is an unique identifier of a compute policy generated by /cloudapi/computePolicies.
- Tested and verified with python script and Postman REST client
- Test for add, remove
- Test to see right exceptions are thrown while adding unknown policy, existing policy
@rocknes @rajeshk2013 @andrew-ni @harshneelmore
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/563)
> [VCDA-1088] pyvcloud: Support for add, remove compute policy to vm(s) of vapp-template

- pyvcloud/vcd/vm.py
VP-2762: [PYSDK] Get sample historic data of a metric
This CLN contains functionality to list samplae historic data of a
metric for a VM.
Testing Done:
Automated test is not possible because it needs VM Monitoring set-up.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/571)
> VP-2762: [PYSDK] Get sample historic data of a metric

- pyvcloud/vcd/client.py
- pyvcloud/vcd/platform.py
- pyvcloud/vcd/vm.py
- system_tests/datastore_tests.py
- system_tests/vm_tests.py
VP-2051: [PySDK] relocate
This CLN contains functionality to relocate VM to other datastore. It
calls POST API of relocate for VM.
Testing Done:
Test method test_0260_relocate is added to test the functionality.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/572)
> VP-2051: [PySDK] relocate

- pyvcloud/vcd/vapp_firewall.py
- system_tests/vapp_firewall_tests.py
VP-2652:[PySDK] Add firewall rule in vapp network
VP-2655: [PySDK]Remove firewall rule in vapp network
VP-2640: [PySDK] update firewall rule default action and log in vapp network
VP-2642: [PySDK]Update firewall rule in vapp network
VP-2778: [PySDK] list firewall rule  in vapp network
This CLN contains Add firewall rule, Remove firewall rule, Update firewall rule,  update firewall rule default action and log, list firewall rule  in vapp network.
set_default_action(), add_firewall_rule(), list_firewall_rule(),  update_firewall_rule() and delete_firewall_rule() methods are exposed in vapp_firewall.py class and corresponding test case added.
Testing Done:
test_0020_set_default_action(), test_0030_add_firewall_rule(), test_0040_list_firewall_rule(),  test_0050_update_firewall_rule() and …
> VP-2652, VP-2655, VP-2640, VP-2642, VP-2778

- pyvcloud/vcd/vapp_nat.py
- system_tests/vapp_nat_tests.py
VP-2750: [PySDK]Enable NAT rule in vapp network
VP-2753: [PySDK]Select NAT rule type in vapp network
This CLN contains Enable NAT rule, Select NAT rule type in vapp network.
enable_nat_service() and update_nat_type() methods are exposed in vapp_nat.py class and corresponding test case added.
Testing Done:
test_0010_enable_nat_service() and test_0020_update_nat_type() are added in test class vapp_nat_tests.py.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/574)
> VP-2750, VP-2753

- pyvcloud/vcd/vapp_nat.py
- system_tests/vapp_nat_tests.py
VP-2744: [PySDK]Add NAT rule in vapp network
This CLN contains add nat rule in vapp network. 
add_nat_rule() method is exposed in vapp_nat.py class and corresponding test case added.
Testing Done:
test_0030_add_nat_rule() is added in test class vapp_nat_tests.py.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/580)
> VP-2744: [PySDK]Add NAT rule in vapp network

- pyvcloud/vcd/vapp_nat.py
- system_tests/vapp_nat_tests.py
VP-2797: [PySDK] List NAT rule in vapp network
VP-2810: [PySDK] get NAT type and policy in vapp network
VP-2748: [PySDK]Delete NAT rule in vapp network
This CLN contains list NAT rule, get NAT type and delete NAT rule in vapp network.
get_nat_type(), get_list_of_nat_rule() and delete_nat_rule() method are exposed in vapp_nat.py class and corresponding test case added.
Testing Done:
test_0040_get_nat_type(), test_0050_get_list_of_nat_rule() and test_0090_delete_nat_rule() are added in test class vapp_nat_tests.py.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/583)
> VP-2797, VP-2810, VP-2748

- pyvcloud/vcd/org.py
- pyvcloud/vcd/vdc.py
- Raise unified exception for unsupported client api versions on compute-policy crud operations.
- Currently, compute policy crud on vdc and vms throw different exceptions depending on the client versions that are not supported. In this PR, changes are made to throw unified exception depending on the client api version.
- Tests done on 9.1, 9.5 and 9.7 vcd with client api versions 29.0, 30.0, 31.0 and 32.0 with scripts 
- No System tests added since there is no access to /cloudapi from pyvcloud. 
- @rocknes @rajeshk2013
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/576)
> [VCDA-1112] pyvcloud: Unified exception for unsupported client versions that use compute policy api

- pyvcloud/vcd/client.py
- pyvcloud/vcd/vm.py
- system_tests/vm_tests.py
VP-2684:[PYSDK] List RunTime Info section
VP-2686:[PYSDK] List BootOptions
VP-2813:[PYSDK] Update boot options
This CLN contains VM's functionalities for runtime info and boot
options.
Testing Done:
Test methods test_0340_list_boot_options, test_0350_update_boot_options
and test_0360_list_runtime_info are added in vm_tests.py file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/584)
> VP-2684,VP-2686,VP-2813: Boot options and runtime info

- pyvcloud/vcd/vapp.py
- pyvcloud/vcd/vapp_nat.py
- system_tests/vapp_nat_tests.py
VP-2746: [PySDK]Update NAT rule in vapp network
This CLN contains Update NAT rule in vapp network.  
update_nat_rule() method is exposed in vapp_nat.py class and corresponding test case added.  
test_0060_update_nat_rule() is added in test class vapp_nat_tests.py.  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/585)
> VP-2746: [PySDK]Update NAT rule in vapp network

- system_tests/vapp_tests.py
Due to suspended vm state test cases it's went in partial state.
That making cause to fail other test cases for temporary .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/588)
> Test Failure

- pyvcloud/vcd/vdc.py
- system_tests/idisk_tests.py
- system_tests/network_tests.py
Unit Test Failure in pyvcloud.
test_0040_list_isolated_orgvdc_networks_as_non_admin_user(0 and test_0050_get_isolated_orgvdc_network_as_non_admin_user() in network_tests.py removed due to design change.
test_0078_remove_static_ip_pool() skip due to bug in vcd.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/591)
> Unit Test Failure in pyvcloud

- pyvcloud/vcd/vm.py
- system_tests/vm_tests.py
This CLN conatins VM metadata set, get, update and remove operations.
Testing Done:
Test methods test_0370_set_meadata. test_0380_get_meadata,
test_0390_update_metadata and test_0400_remove_metadata are added in
vm_tests.py.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/590)
> VP-2620,VP-2855,VP-2848,VP-2850: Metadata CRUD operations

- system_tests/vm_tests.py
Sometimes discard suspended state puts VM in partially suspended state and it
make all next test case to fail.So, commemting suspend state scenerio. In future,
these will be fixed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/592)
> Fixing CI/CD test failures.

- system_tests/extnet_tests.py
Skipping update external network test case because of PR: 2399981
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/595)
> Skipping update external network test case because of PR: 2399981

- pyvcloud/vcd/vapp_static_route.py
- system_tests/vapp_static_route_tests.py
VP-2755: [PySDK]Enable static routing in vapp network
VP-2757: [PySDK]Add static route in vapp network
VP-2759: [PySDK]Update static route in vapp network
VP-2761: [PySDK]Delete static route in vapp network
VP-2812: [PySDK]List static route in vapp network
This CLN contains Enable, Add, Update, Delete and List  static routing in vapp network.
enable_service(), add(), list(), update() and delete() methods are exposed in vapp_static_route.py class and corresponding test case added.
Testing Done:
test_0010_enable_service(), test_0020_add(),  test_0030_list(),  test_0040_update()  and test_0090_delete() are  added in test class vapp_static_route_tests.py.
--- …
> VP-2755, VP-2757, VP-2759, VP-2761, VP-2812

- pyvcloud/vcd/vm.py
- system_tests/vm_tests.py
VP-2661:[PYSDK] update virtualHardwareSection/media
VP-2656:[PYSDK] Update virtualHardwareSection-disks
This CLN contains update operation on VirtualHardwareSection media and
disks.
Testing Done:
Test method test_0440_update_vhs_disk is added. IN the given VM template
update media gives response as 405/METHOD_NOT_ALLOWED, so test case is
not added for update media operation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/601)
> VP-2661,VP-2656: Update VirtualHardwareSection media and disks

- pyvcloud/vcd/client.py
VP-2904: Logger issue in pyvcloud
Bug in pyvcloud wire logging.
All pyvcloud clients share the same logger instance.
Everytime you create a new client, you will end up adding a new handler to the logger
which means each log statement will be printed n times where n = number of created clients
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/605)
> VP-2904: Logger issue in pyvcloud

- pyvcloud/vcd/org.py
[PYVCLOUD]list system-vdc fix.
When we list vdc in system org, it should not print any VDC.Current
behavior is listing existing vdc for other org.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/610)
> VP-2974: [PYVCLOUD]list system-vdc fix.

- pyvcloud/vcd/client.py
[2420217]With api version 33.0 , "vcd vdc use vdc-name " not working
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/612)
> [2420217]With api version 33.0 , "vcd vdc use vdc-name " not working

- pyvcloud/vcd/org.py
VP-3046: [PYSDK] Functionality to provide admin or non admin URL in
list_vdc method.
Implemeting one flag which asks for admin or non admin VDC href in the
list.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/617)
> VP-3046: [PYSDK] Functionality to provide admin or non admin URL in list_vdc method.

- pyvcloud/vcd/vm.py
Added `update_compute_policy` function to **vm.py**
This function takes a compute policy href and id and updates the VM to have the specified compute policy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/615)
> Implement update VM compute policy

- pyvcloud/vcd/vdc.py
Simple fix, resolvs  argument type missmatch issues [618](https://github.com/vmware/pyvcloud/issues/618)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/620)
> Resolvs argument type missmatch issues 618

- pyvcloud/vcd/org.py
Fix #630 : list_rights_available_in_system: bad usage of list_rights_available_in_vcd
Remove self as an arg of `list_rights_available_in_vcd` where it is not expected to be.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/631)
> Fix #630 list_rights_available_in_system

- pyvcloud/vcd/client.py
Fixing issue when executing a typed query using the parameter pageSize : 400 Bad request.
& character is not added on the URI when using the paramater pageSize on the function _build_query_uri. It lealds to a 400 bad request when executing it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/629)
> fix-bug-page-size

- pyvcloud/vcd/org.py
- pyvcloud/vcd/vm.py
Till api v32.0, Compute Policies were associated with VMs via the VdcComputePolicy tag.
In api v33.0, VdcComputePolicy tag was deprecated and replaced by ComputePolicy-VmSizingPolicy tags.
And in api v34.0, VdcComputePolicy will be completely removed.
This PR, reflects the shift in XML tags for associating/disassociating compute policies with/from VMs. The methods to assign/remove compute policies to/from vms in either vApp template or vApp has been modified to take into account VmSizingPolicy (depending on the api version used).
Testing Done : 
Manually tested the following on vCD 9.7, vCD 10.0 and vCD 10.0.0.1
Template used - photon-v2_k8-1.14_weave-2.5.2
* CSE startup with template rule - Success - Assigned policy correctly to template vm
* Deploy cluster on ovdc without compute policy …
> [VCDA-1333] Adding support for VMSizingPolicy while dealing with compute policies on VMs

- pyvcloud/vcd/vm.py
Fixes a bug where only one disk is returned even if there are more.
https://github.com/vmware/pyvcloud/issues/628
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/644)
> fixing bug where only one disk is listed even if there are more

- pyvcloud/vcd/api_client.py
- pyvcloud/vcd/api_helper.py
- requirements.txt
- system_tests/api_client_tests.py
Add a client to provide an uniform way to invoke both REST API and CloudAPI endpoints. The new client is a wrapper over the existing client with some additional features. It uses generated model classes for request and response payloads.
Complete list of features are as follows:-
* Methods to build URI by providing relative resource paths, ex: '/admin/orgs','/1.0.0/roles' etc.
* Generic call_api() method for GET/POST/PUT/DELETE, it accepts/returns model objects and takes care of conversion to/from plain JSON objects.
* Methods to get response status, headers, links and task of the last HTTP call.
* Method to wait for the last task.
* A helper class to build query parameters.
Testing done:
Added a new test class api_client_test.py to perform CRUD on org (REST API) and role (CloudAPI). …
> Add a client with model bindings for REST API and CloudAPI

- AUTHORS
- ChangeLog
- pyvcloud/vcd/client.py
If the query filter has spaces, it is getting endoded twice as %2520 instead of %20. Because of this vCloud returns empty query result.
Removing encoding from _AbstractQuery constructor, _build_query_uri() is already encoding the query filter string.
@rajeshk2013 @rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/646)
> Fix query filter URL encoding

- pyvcloud/vcd/utils.py
Just added the adapterType disk Info on the vm_to_dict function, it's used on **vcd vm info** command.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/654)
> Added disk adaptertype on vcd vm info command

- pyvcloud/vcd/utils.py
- Fix listing disk: `disk` object has no `size` attribute, but `sizeMb`.
Related: https://github.com/vmware/vcd-cli/pull/527
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/660)
> Fix - disk list size

- pyvcloud/vcd/client.py
- system_tests/api_extension_tests.py
* Added support for api version 34.0 and 35.0
* Disabled api extension tests - vCD 10.1 has a backward compatibility big. Will enable them back once the vCD bug is fixed.
Testing done :
Ran the pyvcloud test suite and made sure there are no failures.
Job - sp-tass - CToT4-pysdk-sp-main-Weekly/14/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/666)
> Adding support for api version 34.0 and 35.0 in pyvcloud

- AUTHORS
- ChangeLog
- pyvcloud/vcd/client.py
get_catalog() searches only in the first page of the query records. Due to which the API can fail if number of catalogs are more than default page size i.e 25. This change also fixes another similar issue for vDC.
Testing done:
Ran catalog_tests.py. All tests passed.
Manually tested in an org having more than 25 catalogs, able to get catalog from 2nd page of query records.
@rajeshk2013
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/670)
> [issue-669] get_catalog() func failed with Catalog not found error

- pyvcloud/vcd/api_extension.py
- pyvcloud/vcd/client.py
Adds optional `<Description>description</Description>` child element to the `<vmext:Service>` parent element.
Documentation: https://vdc-repo.vmware.com/vmwb-repository/dcr-public/06a3b3da-4c6d-4984-b795-5d64081a4b10/8e47d46b-cfa7-4c06-8b81-4f5548da3102/doc/doc//operations/PUT-Service.html
Tested; functions work and resulting XMLs look as expected when description is provided/omitted
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/668)
> Add extension description to XML

- pyvcloud/vcd/api_extension.py
- pyvcloud/vcd/client.py
Currently there is no way to update/modify api filters on an api extension service without first deleting the service and then recreating it. This PR introduces two new methods to 
* remove all api filters on an existing api extension service
* add new api filters to an existing api extension service
Testing done:
Tested the two functions via CSE upgrade and the api filters are getting removed and added without any issue without having to delete the service itself.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/675)
> Add methods to remove/add api filters to existing api extension services

- pyvcloud/vcd/vdc.py
`instantiate_vapp` in vdc.py assumes that the current vdc has an up link to the Org. This is not true when using an unprivileged account like vApp Author, that has certain access to public catalogues.
This patch allows to fetch the current Org from the client, which will be the one we are working with for this VDC (the unprivileged user does not have visibility on other tenants like the SYSTEM account)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/671)
> Get the Org from the Client if find_link fails in instantiate_vapp()

- pyvcloud/vcd/vdc.py
When instantiating a new vApp from a template that has an existing vApp network, the current code attempts to look for this vApp network in the list of VDC networks, which results in an 400 error and EntityNotFoundException. To correct this, we skip the exception if we encounter a template network, which lets vCloud Director correctly handle the vApp network.
Fixes https://github.com/vmware/pyvcloud/issues/682.
Tested on an internal vCloud Director instance @ VMware, and verified that the changes made here correctly propagate to [`vcd-cli`](https://github.com/vmware/vcd-cli/) and [`ansible-module-vcloud-director`](https://github.com/vmware/ansible-module-vcloud-director).
--- …
> Correctly ignore vApp networks when instantiating from template

- pyvcloud/vcd/client.py
- pyvcloud/vcd/platform.py
- system_tests/base_config.yaml
- system_tests/host_tests.py
- system_tests/run_system_tests.sh
This PR adds 5 methods for working with hosts:
- list_hosts()
- get_host(name)
- enable_disable_host(name, enable_flag) => Although deprecated since API 31.0.
- prepare_host(name, username, password) => Although deprecated since API 31.0.
- unprepare_host(name) => Although deprecated since API 31.0.
Unfortunately, I was not able to write some tests for those, as I don't have a local vCD instance and our environments don't have internet access for installing the dependencies. However, as the code is not very special that shouldn't be a problem, one can add the tests later. Additionally, we are already using it in production.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/3 …
> Add methods for hosts to platform

- pyvcloud/vcd/utils.py
- pyvcloud/vcd/vm.py
Fixed following issues:
1. `utils.task_to_dict` returned `task.Details` as `StringElement` and not `str`.
2. `utils.task_to_dict` didn't include the `href`, which is needed by TaskMonitor.
3. `vm.list_nics` failed when no nic is attached to vm (no attribute `NetworkConnection`).
4. `utils.pvdc_to_dict` failed with "no such child attribute error" when Description is not available.
5. `utils.vm_to_dict` failed with "no such child attribute error" when GuestCustomization is not enabled.
6. `utils.vm_to_dict` failed with "no such child attribute error" when VirtualHardwareSection is not available.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/622)
> Bugfixes for *_to_dict and list_nics methods

- pyvcloud/vcd/client.py
- pyvcloud/vcd/vapp.py
- pyvcloud/vcd/vdc.py
- pyvcloud/vcd/vm.py
This PR adds 7 methods:
- VDC:
- get_resource_admin()
- query_vm_by_name(name)
- get_vc()
- ~~VApp~~:
- ~~set_name(name)~~
- VM:
- discard_suspended_state()
- ~~set~~edit_name(name)
- ~~set~~edit_hostname(hostname)
Unfortunately, I was not able to write some tests for those, as I don't have a local vCD instance and our environments don't have internet access for installing the dependencies. However, as the code is not very special that shouldn't be a problem, one can add the tests later. Additionally, we are already using it in production.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/367)
> Add several methods to vdc, vapp and vm

- pyvcloud/vcd/vm.py
Remove print of storage policy, as mentioned in issue #676.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/689)
> Remove print (#676)

- pyvcloud/vcd/client.py
- pyvcloud/vcd/pvdc.py
- pyvcloud/vcd/vdc.py
- system_tests/pvdc_tests.py
This PR adds 6 methods for working with storage profiles:
- PVDC:
- get_storage_profiles()
- get_storage_profile(profile_name)
- VDC:
- get_default_storage_profile()
- add_storage_profile(profile_name, enabled=True, default=False, limit_in_mb=0)
- update_storage_profile(profile_name, enabled, default=None, limit_in_mb=None)
- remove_storage_profile(profile_name)
Unfortunately, I was not able to write some tests for those, as I don't have a local vCD instance and our environments don't have internet access for installing the dependencies. However, as the code is not very special that shouldn't be a problem, one can add the tests later. Additionally, we are already using it in production.
--- …
> Add methods for storage profiles to pvdc and vdc

- pyvcloud/vcd/org.py
- pyvcloud/vcd/utils.py
- Templates created by pyvcloud currently specify VmSizingPolicyFinal and VmPlacementPolicyFinal as "false" all the time.
* Create optional parameters to specify if the compute policies can be modified. Change the util method to include parameters for vmSizingPolicyFinal and VmPlacementPolicyFinal.
- Testing done:
Tried associating the template with a placement policy and checked if the "Modifiable" check box is not checked from the UI
Creating cluster from CSE without publishing placement policy associated with the VM and the creation of cluster failed (expected)
@rocknes @sahithi @sakthisunda @andrew-ni
---
This change is [<img …
> Add option to specify if compute policy is modifiable

- pyvcloud/vcd/vm.py
When we use Ansible VMware vCloud Director modules from:
https://github.com/vmware/ansible-module-vcloud-director
When we **add_nic()** are first, after successful complete adding module fail with error about referenced variable which called before assigment.
When we use [Ansible Module](https://github.com/vmware/ansible-module-vcloud-director), and inside Ansible module calling list_nics() on adding time (list_nics called afer add_nic), we crash after successful adding the NIC - Fatal error, what try to say about first added NIC and him "**primary_index**", _**which referenced before assignment**_.
[feat2RFC(vcd_vapp_vm_nic): Do a module invocation better #131](https://github.com/vmware/ansible-module-vcloud-director/pull/131)
[gist_exception_example](https://gist.github.com/westsouthnigh …
> Fixing error in list_nics(self): primary_index referenced before assignment

- pyvcloud/vcd/utils.py
- pyvcloud/vcd/vapp.py
Support Addition of placement policies during vm creation
* changed the util function `generate_compute_policy_tags()` to accept placement policy so that placement policy tag will also be created.
* Since there is no need to send `VdcComputePolicy` tag for request to create the vm for api version >= 33.0, Avoided sending in the tag.
Testing:
* Made use of the function to create a cluster in CSE with placement policy and sizing policy.
- tested with only placement policy
- tested with both placement policy and sizing policy
@rocknes @sahithi @sakthisunda
--- …
> Support addition of placement policy during adding vms to vapps

- pyvcloud/vcd/client.py
This commit updates rel value ResourceType.PORT_GROUP
from `portGroup` to `portgroup`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/699)
> Updating rel value for ResourceType.PORT_GROUP

- pyvcloud/vcd/client.py
- pyvcloud/vcd/org.py
Signed-off-by: ltimothy <ltimothy@vmware.com>
Added support for including the tenant context header (X-VMWARE-VCLOUD-TENANT-CONTEXT) when creating an org. This change allows a non-system-admin user to create a catalog in another org.
Adding this support included the client POST request having an added param: extra_headers. To generalize this change, this extra param was added to GET and DELETE client requests.
---
This change is [<img …
> Include tenant context header when creating catalog

- pyvcloud/vcd/api_extension.py
- pyvcloud/vcd/client.py
- pyvcloud/vcd/external_network.py
- pyvcloud/vcd/org.py
- pyvcloud/vcd/platform.py
- pyvcloud/vcd/system.py
- pyvcloud/vcd/task.py
- pyvcloud/vcd/vdc.py
- system_tests/nsxt_tests.py
For api v35.0+, vCD requires special characters viz. ( ) ; , to be escaped if used as value in query filter.
In _AbstractQuery, we escape the special characters in encoded filter value.
Additional changes, 
1. Replaced usage of quote_plus to quote, since quote_plus will replace spaces with + and thus can cause the filter value to distort.
2. Encoded all usage of qfilter in get_typed_query, since this field should be encoded by caller.
Testing done:
Ran all vcd-cli commands that invoke the affected methods at api v35.0 and made sure that all these commands returned expected result.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/711)
> Add support to escape special characters in query filter for api v35.0+

- pyvcloud/vcd/client.py
- pyvcloud/vcd/gateway.py
This commit has the following two changes, …
1. Parses the returned response based on the
set `accept_type` value
2. Updates the output of gateway's list_static_routes`
Resolved: #731
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/732)
> Parse the returned response based on the set `accept_type` value

- examples/list-vapps.py
- examples/system-info.py
API version is hard coded as "29.0" in some of the files under examples. Removed them and setting highest supported API version. 
Testing done:
Ran examples/run_examples.sh, works with latest cloud director. 
- @rajeshk2013
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/755)
> Remove hardcoding of API version from examples

- pyvcloud/vcd/client.py
- pyvcloud/vcd/vapp.py
Storage profile element should be added before compute policy element in recompose Vapp call
Testing done:
Create VM via CSE and verify if proper storage profile is added to the VM.
@rocknes @sakthisunda
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/761)
> [VCDA-2334] Storage profile element should cbe added before compute policy

- pyvcloud/vcd/vm.py
- Support for getting vm extra config information
- New method to get extra config elements
- Tested by python script:
- create a vm
- set extra config key:value using vmtools
- Get using the new method that is implemented for this PR 
- verified the test data set is present in the returned dictionary
@rocknes @Anirudh9794
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/765)
> [VCDA-2386] Method to get extra config information of vm

- pyvcloud/vcd/client.py
Downloading a media fails with, Error: 'list' object has no attribute 'items'.
Error is coming from client._log_request_sent() method. Default value of headers should be an empty map not list.
Testing done:
Manually verified that media download from vcd-cli passes.
- @rajeshk2013
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/769)
> Fix media download

- pyvcloud/vcd/client.py
- pyvcloud/vcd/vcd_api_version.py
- requirements.txt
Create a version class for easy comparison of version objects
Testing done:
* Checked if comparisons are as expected.
* Added 37-alpha version to supported api version list
* Checked if login works properly after the changes
@rocknes @sakthisunda
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/pyvcloud/776)
> [VCDA-2669] Add VCDApiVersion object for easy version comparison
